### ISSUE TITLE
Can serilog-sinks-file support a more file naming strategy?

### ISSUE THREAD

**Issue by okman523** [serilog/serilog-sinks-file#105]
Hi, I have an idea, serilog-sinks-file can support the following file naming strategy: (assuming the log file is named log.txt):
     The name of the latest log file is always log.txt. When the Rolling policy is triggered, the log file name is changed to log2019070114.txt or log_002.txt according to the policies of rollingInterval and rollOnFileSizeLimit.
   The advantage of this is that you always know that log.txt is the latest log file, so that other programs can read and write the latest logs.

**Comment by cocowalla** [comment]
Thanks for the suggestion! This is already tracked by #40, so any discussion can continue there :+1:
