### ISSUE TITLE
Allow user to execute custom action on deprecated files (ex. move or send to different server)

### ISSUE THREAD

**Issue by nogard111** [serilog/serilog-sinks-file#106]
Can we allow different action on obsolete files ?
I think it would be beneficial in situation when old logs should be archived by moving to different folder or different server (dedicated only for logs)

 `     /// Action that should be preformed on obsolete(old) log files` 
`         public static Action<string> OnObsoleteFile = null;`

Inside remove loop:

```
          foreach (var obsolete in toRemove)
            {
                var fullPath = Path.Combine(_roller.LogFileDirectory, obsolete);
                try
                {
                    if(OnObsoleteFile!= null)
                        OnObsoleteFile.Invoke(fullPath);
                    else
                    {
                        System.IO.File.Delete(fullPath);
                    }
                }
                catch (Exception ex)
                {
                    SelfLog.WriteLine("Error {0} while processing obsolete file {1}", ex, fullPath);
                }
            }
```

It is more like example, not working code :)

**Comment by cocowalla** [comment]
It's not *exactly* what you describe, but [FileLifecycleHooks](https://github.com/serilog/serilog-sinks-file/blob/36381f6446d79a0c0c8d7eb1a32aec223d35fc1d/src/Serilog.Sinks.File/Sinks/File/FileLifecycleHooks.cs) (available in the preview version) should cover you here.

It allows you to hook in before a new log file is opened, so you can do things like wrap the output stream in a compressing or encrypting stream, add a custom header etc. But at this point you could also scan the log folder for old files that you want to ship, compress, sign,encrypt, delete or whatever.

You can see an example implementation at [/cocowalla/serilog-sinks-file-header](https://github.com/cocowalla/serilog-sinks-file-header).

**Comment by nblumhardt** [comment]
Sounds like a great candidate for an `OnFileRemoving()` hook. Interested in helping to push this through, if you're keen to PR it, @nogard111 ?

**Comment by cocowalla** [comment]
@nblumhardt presumably this would only apply to `RollingFileSink`?

Do we want the presence of an `OnFileRemoving()` hook to mean "the caller will completely handle retention, Serilog does nothing", or "the caller will do something, then Serilog is responsible for deleting the file"?

In terms of API, we could have:
`public abstract void OnFileRemoving(string filename);`

or maybe
`public abstract bool OnFileRemoving(string filename);`

The idea with the latter being that the `bool` signifies whether Serilog should continue to delete the file as normal.

**Comment by nogard111** [comment]
I put PR , It you see some improvements/issues please let me know

**Comment by cocowalla** [comment]
Just a note to say there is a new FileLifecycleHooks-based plugin available that uses this `OnFileDeleting` hook to archive obsolete files, [serilog-sinks-file-archive](https://github.com/cocowalla/serilog-sinks-file-archive)
