### ISSUE TITLE
Allow to configure sink with constructor

### ISSUE THREAD

**Issue by olsh** [serilog/serilog-sinks-file#112]
ElasticSearch sink has the feature [`FailureSink`](https://github.com/serilog/serilog-sinks-elasticsearch#handling-errors).
In order to configure it, you should create a sink object, like this:
```csharp
FailureSink = new FileSink("./failures.txt", new JsonFormatter(), null)
```

The issue is that [the FileSink constructor marked as obsolete](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Sinks/File/FileSink.cs#L48) and doesn't support many configuration options.

It would be nice to have to configure it with the constructor for such cases.

**Comment by nblumhardt** [comment]
Thanks for the note.

Many Serilog sinks avoid a public constructor, so ideally the ElasticSearch sink would support this by calling the `LoggerSinkConfiguration.Wrap()` method, and expose an API like:

```csharp
FailureSink = writeTo => writeTo.File(...);
```

This would open up a lot more sink options, so maybe one to consider there as a first preference.

**Comment by nblumhardt** [comment]
Closing as I think this is an issue with the ES sink; suggested fix in the linked issue, if anyone is interested in PRing it over there.
