### ISSUE TITLE
Multiple File Sinks with different Filters write the same Logs

### ISSUE THREAD

**Issue by Sonorpearl** [serilog/serilog-sinks-file#114]
I´ve configured or at least tried to with help of the documentation and other issues, multiple Rolling File Sinks. I want to Filter them by only including certain Namespaces into one Logfile. But in the end, every Logfile has the same Logs. It´s probably just syntax or it is a problem with the filters, I´ve tried a few things, but nothing has worked. Help is greatly appreciated.

I´m using ASP.NET Core and the Serilog Configuration via the appsettings file.

```
{

  "Serilog": {
    "Using": [
      "Serilog.Sinks.Debug",
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File"
    ],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Debug"
      },
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
        }
      },
      {
        "Name": "File",
        "Args": {
          "restrictedToMinimumLevel": "Error",
          "path": "logs\\error.log",
          "fileSizeLimitBytes": 1000000,
          "retainedFileCountLimit": 2,
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
        }
      },
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "WriteTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "logs\\Namespace1.log",
                  "fileSizeLimitBytes": 1000000,
                  "retainedFileCountLimit": 2
                }
              }
            ],
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "StartsWith(SourceContext, 'Namespace1')"
                }
              }
            ]
          }
        }
      },
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "WriteTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "logs\\Namespace2.log",
                  "fileSizeLimitBytes": 1000000,
                  "retainedFileCountLimit": 2
                }
              }
            ],
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "StartsWith(SourceContext, 'Namespace2')"
                }
              }
            ]
          }
        }
      },
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "WriteTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "logs\\Namespace3.log",
                  "fileSizeLimitBytes": 1000000,
                  "retainedFileCountLimit": 2
                }
              }
            ],
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "StartsWith(SourceContext, 'Namespace3')"
                }
              }
            ]
          }
        }
      },
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "WriteTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "logs\\Namespace4.log",
                  "fileSizeLimitBytes": 1000000,
                  "retainedFileCountLimit": 2
                }
              }
            ],
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "StartsWith(SourceContext, 'Namespace4')"
                }
              }
            ]
          }
        }
      }
    ],
    "Enrich": [
      "FromLogContext"
    ],
    "Properties": {
      "Application": "Test"
    }
  }
}
```

**Comment by cocowalla** [comment]
Could you post your csproj file for the project in question please, or at a minimum all the `PackageRef` elements for `Serilog.*` Nugets?

**Comment by Sonorpearl** [comment]
<PackageReference Include="Serilog.AspNetCore" Version="3.0.0" />
    <PackageReference Include="Serilog.Filters.Expressions" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.SyslogMessages" Version="1.0.3" /

That are my Nuget Packages, but somehow it just started working today, after a good old computer restart...

**Comment by cocowalla** [comment]
@Sonorpearl I can only guess that the Serilog.Filters.Expressions package wasn't restored for some reason.

**Comment by fernandowolff** [comment]
For people that gets here and it was still not working. My problem was the syntax on 
```"Filter": [{...}]```
I was defining like ```"Filter": {...}```, instead ```"Filter": [{...}]``` as Sonorpearl did above. After adjusting that, filters started to work and each file now contains only the namespace we specified there.

**Comment by prashu2439** [comment]
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.File" ],
    "MinimumLevel": {
      "Default": "Warning",
      "Override": {
        "Microsoft.Hosting.Lifetime": "Debug", // Set a lower level to capture more logs before filtering
        "Your.Other.SourceContext": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "Logs/hosting_lifetime_log.txt",
          "restrictedToMinimumLevel": "Debug", // Capture Debug and above
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
          "fileSizeLimitBytes": 10485760,
          "rollingInterval": "Day",
          "retainedFileCountLimit": 10,
          "rollOnFileSizeLimit": true,
          "shared": true
        },
        "Filter": [
          { "Name": "ByExcluding", "Args": { "expression": "SourceContext = 'Microsoft.Hosting.Lifetime' and Level = 'Information'" } }
        ]
      },
      {
        "Name": "File",
        "Args": {
          "path": "Logs/other_source_context_log.txt",
          "restrictedToMinimumLevel": "Verbose", // Capture all levels
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
          "fileSizeLimitBytes": 10485760,
          "rollingInterval": "Day",
          "retainedFileCountLimit": 10,
          "rollOnFileSizeLimit": true,
          "shared": true
        },
        "Filter": [
          { "Name": "ByIncludingOnly", "Args": { "expression": "SourceContext = 'Your.Other.SourceContext'" } }
        ]
      }
    ]
  }
}

**Comment by prashu2439** [comment]
How to write log using serilog for two different filters

**Comment by prashu2439** [comment]
using System;
using ClosedXML.Excel;

class Program
{
    static void Main(string[] args)
    {
        int rows = 10; // specify the number of rows
        int columns = 5; // specify the number of columns

        GenerateCellReferences(rows, columns);
    }

    static void GenerateCellReferences(int rows, int columns)
    {
        for (int col = 1; col <= columns; col++)
        {
            for (int row = 1; row <= rows; row++)
            {
                string cellReference = GetColumnLetter(col) + row;
                Console.WriteLine(cellReference);
            }
        }
    }

    static string GetColumnLetter(int columnNumber)
    {
        int dividend = columnNumber;
        string columnName = String.Empty;
        int modulo;

        while (dividend > 0)
        {
            modulo = (dividend - 1) % 26;
            columnName = Convert.ToChar(65 + modulo) + columnName;
            dividend = (dividend - modulo) / 26;
        }

        return columnName;
    }
}

**Comment by prashu2439** [comment]
How to generate cell values using rows and columns

**Comment by cocowalla** [comment]
> How to generate cell values using rows and columns

With all due respect, this isn't a general support forum for all your programming questions. I think your questions are better suited for Stackoverflow.
