### ISSUE TITLE
Allow option to keep root log file as most recent

### ISSUE THREAD

**Issue by etreff-tillster** [serilog/serilog-sinks-file#115]
Assuming the following:
1. I want to use file rolling based on size
2. I am saving to path ".\MyLog.log"
3. My file limit is 10mb
4. My file retention limit is 5 files

Once MyLog.log is full a new file, MyLog_001.log (or whatever), will be created and writing will continue in this new file. I would like the option to have MyLog.log copied to MyLog_001.log and writing continue in a now cleared out MyLog.log file. 

This is the same behavior that Log4Net has with their rolling files. _Each time the primary file rolls over, instead of writing to a new file, all previous files are copied and their filenames are incremented by 1. The primary file is then cleared and writing resumes in that same file. Assuming retention limit of 5 files, this means that MyLog_005.log contains the **oldest** data, not the newest data._

This type of behavior is beneficial for our QA team as they can keep a single file open in their editor and know that it will always contain the most recent log info.

**Comment by cocowalla** [comment]
Hi, I think the behaviour you are asking for is covered by #40, so discussion can continue over there if you want to - thanks!
