### ISSUE TITLE
Add file lifecycle hook when file is rolled

### ISSUE THREAD

**Issue by gregbair** [serilog/serilog-sinks-file#120]
Currently, [`FileLifecycleHooks`](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Sinks/File/FileLifecycleHooks.cs) has two hooks - file open and file deleted.

I'd like to have one for when the file is rolled. I'd like to use this to perform some action on the rolled file (compression, etc).

I can try to get a PR in for this this week or next, if that's acceptable

**Comment by nblumhardt** [comment]
It would be great to get a sketch of how this might work (when the hook would be triggered, what guarantees would be offered, etc.) - definitely open to this, but needs some initial design sketches ahead of implementation 👍

**Comment by nblumhardt** [comment]
Closing as stale, but keen to continue discussion if anyone's able to investigate the finer points of this design. Cheers!
