### ISSUE TITLE
[Question] - Remove newline chars from Exception details?

### ISSUE THREAD

**Issue by cesar-moya** [serilog/serilog-sinks-file#122]
Hello, I'm using this sink to write to file, I noticed that when using Log.Exception it adds return/newline characters, is there a way to prevent this? for instance to escape the exception inner string to remove these newline characters globally?

Note: I'm using this outputTemplate:
outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss zzz} [{Level:u3}] {Message:lj}{Exception}{NewLine}")

Thanks!

**Comment by nblumhardt** [comment]
You'll need to write an `ILogEventEnricher` and plug it in using `Enrich.With()`; the enricher needs to create a new property, `_Exception`, without the newlines, and this property name can then be used in the template. Should be some similar enricher examples online. HTH!
