### ISSUE TITLE
Support for path by date.

### ISSUE THREAD

**Issue by snowchenlei** [serilog/serilog-sinks-file#125]
The first problem：

- Support for path by date.
example: c:/Demo/2019/12/info20191231.log
example: c:/Demo/2020/1/info20190101.log

The second problem：
- framework log and customer log stored separately
ByIncludingOnly how to filter.
example: c:/Demo/2019/12/frameworkInfo20191231.log
example: c:/Demo/2019/12/customerInfo20191231.log

**Comment by cocowalla** [comment]
For the first question, I don't think it's possible to specify a "dynamic" path to a sink, where that will change after initial config. But I think you might be able to use [FileLifecycleHooks] (https://github.com/serilog/serilog-sinks-file/blob/9a0257e5b1cdfc170847be456d72dd2c80b45d75/src/Serilog.Sinks.File/Sinks/File/FileLifecycleHooks.cs) to achieve this, by opening a file of your choosing and returning the stream. 

[Serilog.Sinks.Map](https://github.com/serilog/serilog-sinks-map) is one approach to your second question, filtering logs to sinks based on property values.
