### ISSUE TITLE
{Date} includes literal {Date} in file-name

### ISSUE THREAD

**Issue by jgrandydev** [serilog/serilog-sinks-file#127]
`Asp.Net Core 2.2.0`
`Serilog 2.9.0`
`Serilog.Sinks.File 4.1.0`

`appSettings.json`

```
"Serilog": {
  "WriteTo": [
    { "Name": "File",
      "Args": {
        "path": ".\\Logs\\MyApplication-{Date}.log",
        }
    }
  ],
},
```
  
File is created as `MyApplication-{Date}20200127.log`

**Comment by cocowalla** [comment]
I think you're getting this sink mixed up with the deprecated [serilog-sinks-rollingfile sink](https://github.com/serilog/serilog-sinks-rollingfile).

While `serilog-sinks-rollingfile` supported replacing the `{Date}` token with the actual date, this is no longer required with this sink - instead, if you configure rolling based on date, the date will automatically be added to the end of the filename.

**Comment by jgrandydev** [comment]
But what if we want the date located somewhere other than the end of the filename ?  And what if we want date formatted differently than yyyymmdd ?

**Comment by cocowalla** [comment]
That's not supported OOTB, but I think you could achieve it with [FileLifecycleHooks](https://github.com/serilog/serilog-sinks-file/blob/9a0257e5b1cdfc170847be456d72dd2c80b45d75/src/Serilog.Sinks.File/Sinks/File/FileLifecycleHooks.cs)

**Comment by Deilan** [comment]
> That's not supported OOTB, but I think you could achieve it with [FileLifecycleHooks](https://github.com/serilog/serilog-sinks-file/blob/9a0257e5b1cdfc170847be456d72dd2c80b45d75/src/Serilog.Sinks.File/Sinks/File/FileLifecycleHooks.cs)

Went to https://github.com/serilog/serilog-sinks-file/issues/243
