### ISSUE TITLE
Get currently active logging file?

### ISSUE THREAD

**Issue by ChristianSauer** [serilog/serilog-sinks-file#129]
Hi,
is there a way to get the currently active logging File?
I want to expose it via HTTP (don't ask...) and would like to know which file I need to expose.

**Comment by cocowalla** [comment]
I guess you could scan the folder and pick out the file with the latest "last modified" time?

Otherwise, I'm not sure there a *good* way to do this :thinking:. You could use [`FileLifecycleHooks`](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Sinks/File/FileLifecycleHooks.cs), so you would know whenever a new file was opened. Something like:

```c#
public class MyHooks : FileLifecycleHooks
{
    private readonly MyDep dep;

    public MyHooks(MyDep dep)
    {
        this.dep = dep;
    }

    public override Stream OnFileOpened(Stream underlyingStream, Encoding _)
    {
        var filename = ((FileStream)underlyingStream).Name;
        myDep.Notify(filename);
        
        return base.OnFileOpened(underlyingStream, encoding);
    }
}
```

**BUT**, this will only work if your logger doesn't have `fileSizeLimitBytes` set, otherwise the underlying stream will be a `WriteCountingStream` instead of a `FileStream` - `WriteCountingStream` doesn't expose the filename, or provide access to it's own underlying stream.

@nblumhardt do you see any other way to get the current filename? I'm wondering too if `WriteCountingStream` should provide a means to access it's own underlying stream?

**Comment by ChristianSauer** [comment]
Thanks for the quick reply!
The idea with the folder would definitely work, altough I prefer using an inbuilt mechanism. SImply due to the fact that I don't want to guess wrong ;)
Your LiceCycleHook looks good, except the problem with the WriteCountingStream - I think I will go with the first solution and provide a hook to plugin a better function at a later time.

**Comment by Khaos66** [comment]
Based on the answer of @cocowalla I created this solution. Not super clean, as it uses reflection, but should be safe
```C#
internal class LogFileLifecycleHooks : FileLifecycleHooks
{
    public Action<string> FileNameChanged { get; set; }

    public LogFileLifecycleHooks(Action<string> fileNameChanged)
    {
        FileNameChanged = fileNameChanged;
    }

    public override Stream OnFileOpened(Stream underlyingStream, Encoding encoding)
    {
        var streamType = underlyingStream.GetType();
        if (streamType.FullName == "Serilog.Sinks.File.WriteCountingStream")
        {
            var streamField = streamType.GetField("_stream", BindingFlags.NonPublic | BindingFlags.Instance);
            underlyingStream = streamField.GetValue(underlyingStream) as Stream;
        }
        if (underlyingStream is FileStream stream)
        {
            string filename = stream.Name;
            FileNameChanged?.Invoke(filename);
        }

        return base.OnFileOpened(underlyingStream, encoding);
    }
}
```

**Comment by worthapenny** [comment]
Hi,

I am struggling to understand the usage in order to get the active log file path. This is how I tried and the `Path` I get is `null`.

```cs
var logFilePath = Path.Combine(Path.GetTempPath(), "__MyApp_Log..Log");
var filePathHook = new CaptureFilePathHook();

Log.Logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .MinimumLevel.ControlledBy(LoggingLevelSwitch) // Default's to Information 
    .WriteTo.Console(outputTemplate: logTemplate, theme: AnsiConsoleTheme.Code)
    .WriteTo.File(
        logFilePath,
        rollingInterval: RollingInterval.Day,
        retainedFileCountLimit: 7,
        flushToDiskInterval: TimeSpan.FromSeconds(5),
        outputTemplate: logTemplate,
        hooks: filePathHook)
    .CreateLogger();

LoggingLevelSwitch.MinimumLevel = logEventLevel;

var logFIleFullPath = filePathHook.Path; // <---- is null

// .....
class CaptureFilePathHook : FileLifecycleHooks
{
    public string? Path { get; private set; }

    public override Stream OnFileOpened(string path, Stream underlyingStream, Encoding encoding)
    {
        Path = path;
        return base.OnFileOpened(path, underlyingStream, encoding);
    }
}
```

**Comment by GeoDirk** [comment]
@worthapenny 

My code which is similar to your works in returning a path.  The only difference that I could see is that my code goes to a type of `Serilog.Core.Logger` instead of your `Log.Logger`.


```           
var log = new LoggerConfiguration()
                .MinimumLevel.Is(logLevel)
                .WriteTo.File(logPath, outputTemplate: outputTemplate, rollingInterval: RollingInterval.Day, hooks: logFilePathHook)
                .WriteTo.Debug(outputTemplate: outputTemplate)
                .CreateLogger();
```

**Comment by augustoproiete** [comment]
@worthapenny This is because you're not writing anything to the log, and the hook was not yet initialized... You can put a breakpoint the `OnFileOpened` method of your hook to confirm.

```csharp
Log.Information("Hello");
var logFileFullPath = filePathHook.Path; // <----should have the path of the current file
```

**Comment by emilaz** [comment]
What if I need to access the filepath at a different place than where I defined the filePathHook? Can I get it from `Log` somehow?

**Comment by augustoproiete** [comment]
@emilaz Make sure the file path hook updates a shared variable that you can access from the place you need in your app.

**Comment by hhgm** [comment]
> @emilaz Make sure the file path hook updates a shared variable that you can access from the place you need in your app.

So, Ihave managed to get this example working, but you mention sharing the path through shared variable... how would I do this?

**Comment by augustoproiete** [comment]
@hhgm Create a public property on the hook that you can access to retrieve the path. Like the example above https://github.com/serilog/serilog-sinks-file/issues/129#issuecomment-1141428477

**Comment by ShadyHarbinger** [comment]
How can I get the path if the file logger is configuration is red from appsettings?
`
            var logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .Enrich.FromLogContext()
                .CreateLogger();
`
