### ISSUE TITLE
RollingFileSink _currentFileSequence overflow leads to an infinite loop

### ISSUE THREAD

**Issue by trionia** [serilog/serilog-sinks-file#131]
There is a log file that is going to roll, and its name suffix is Int32.MaxValue, a logger goes into an infinite loop.
When the log file reaches it's size limit, `AlignCurrentFileTo` method gets called with an argument `nextSequence=true`.
[RollingFileSink.cs#L106](https://github.com/serilog/serilog-sinks-file/blob/a015038cdba0a38caa4feb73a78bb85ac0a3464b/src/Serilog.Sinks.File/Sinks/File/RollingFileSink.cs#L106)
```cs
                int? minSequence = null;
                if (nextSequence)
                {
                    if (_currentFileSequence == null)
                        minSequence = 1;
                    else
                        minSequence = _currentFileSequence.Value + 1;
                }
```
When `_currentFileSequence.Value` is `Int32.MaxValue`, adding 1 to it results in an overflow, so `minSequence` becomes `Int32.MinValue`.
[RollingFileSink.cs#L142](https://github.com/serilog/serilog-sinks-file/blob/a015038cdba0a38caa4feb73a78bb85ac0a3464b/src/Serilog.Sinks.File/Sinks/File/RollingFileSink.cs#L142)
```cs
            var sequence = latestForThisCheckpoint?.SequenceNumber;
            if (minSequence != null)
            {
                if (sequence == null || sequence.Value < minSequence.Value)
                    sequence = minSequence;
            }

```
Later, the second if statement fails on the condition `sequence.Value < minSequence.Value`; `sequence` remains with its old value, file path remains the same. Since the file reached it's size limit `AlignCurrentFileTo` method is getting called again with `nextSequence=true` and the cycle repeats.

Having two billion rolls is rather unlikely to happen, I was just playing around with the library and thought "what if".

**Comment by cocowalla** [comment]
Hah, nice find!

Would be great if you could have a stab at a PR for a failing test for this bug? Something like `FilesShouldContinueRollingOnOverflow`
