### ISSUE TITLE
Writing to a file stored in a network drive with Credentials

### ISSUE THREAD

**Issue by kisalay1988** [serilog/serilog-sinks-file#134]
I am trying to store log information to a file which is to be saved in a shared network path say \\10.100.9.8\Folder\LogFile.txt and to access this drive credentials with username and password is required but I am not able to achieve.

Has anyone tried this. Some help needed here :)

**Comment by cocowalla** [comment]
I'm not sure this is a Serilog-specific issue, but this should work already if the app is already running under a user account `User1`, and `User1` has been granted write access to the `\\10.100.9.8\Folder` network path.

If however the app is running under an account that *doesn't* have access to the network path, well, don't do that 😄  If for some reason you have to, I would guess that if you make the connection in your code before configuring Serilog, then Serilog would presumably be able to write to it. I don't think this is possible with pure managed code though - there is a [Stackoverflow question](https://stackoverflow.com/questions/295538/how-to-provide-user-name-and-password-when-connecting-to-a-network-share) you may find useful if you want to go down this route.

**Comment by kisalay1988** [comment]
@cocowalla ... Hey.. Thanks for your reply.. Let me put some more light..

The application I am building is a .NET Core Web API and would be accessible within/outside the organization. The shared drive which I have is internal to organization and has a fixed username and password only limited to this path. I am not able to understand where to put these credentials. This is how I have configured in appSettings.json. Along with File I am using Console and MSSqlServer which are working fine

```csharp
"Serilog": {
    "MinimumLevel": "Information",
    "Using": [
      "Serilog.Sinks.Async",
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File"
    ],
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "File",
              "Args": {
                "path": "\\\\10.100.9.8\Folder\\Log_{Date}.json",
                "restrictedToMinimumLevel": "Information",
                "rollingInterval": "Day",
                "shared": true
              }
            },
            {
              "Name": "Console",
              "Args": {
                "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
                "restrictedToMinimumLevel": "Information"
              }
            }
          ]
        }
      }
    ]
  }
....
```
Calling the respective events to log say... 

```csharp
Log.Information("{@value", value);
...
```

**Comment by cocowalla** [comment]
Serilog doesn't have anything built-in to connect to SMB shares, and I don't think that should be part of a logging library; so there isn't anything you can configure in Serilog itself.

4 options I can think of:

1. Given you want to write to a UNC path, presumably your web API is running on Windows. Run it using a service account, and grant that service account write access to the UNC path - this is the "standard" way of doing things
2. Manually connect to the UNC path prior to configuring Serilog. You could do this by pinvoke'ing the Windows API, or your code could run Windows' `net use` command such as `net use \\10.100.9.8\Folder /user:myUser myPassword`
3. If you need to write logs to a central location, consider another means, such as the Windows Event Log with WEF, or syslog
4. Consider if you really need to write these logs to another server - it might be enough to log them locally instead

I hope you find something useful in there 🙂

**Comment by arvindkumarsharma** [comment]
Hi cocowalla, 
Could please provide any example to write log's on network shared location (remote machine) using serilog.
Thanks & Regards,
Arvind Sharma
