### ISSUE TITLE
Option to Lazily Create File on Disk (to Prevent Blank File Creation)

### ISSUE THREAD

**Issue by sdepouw** [serilog/serilog-sinks-file#140]
In my scenario, I have a simple one-off application that I really only want to have logging when errors occur. I have the sink configured to only log on Error level or higher, but after the application runs this sink still creates a file even though it was never used.

I would like to have some configuration option to instruct the sink to delay opening/creating a log file until it has something to write. This would satisfy the feature request of "don't create blank files" as it will never go through the process of creation in the first place. This option, of course, can be disabled by default, so existing usages of the sink are not broken or changed.

I have partially achieved this via a workaround using Sinks.Map, since it has built-in deferral of execution. See full details [in my StackOverflow question](https://stackoverflow.com/q/61111842/100534). However, it is a workaround/hack and isn't even fully-supported, as the deferred code will still get called even though my minimum `LogEventLevel` is set (which is ignored here because Map doesn't consider it).

**Comment by nblumhardt** [comment]
Hi! Thanks for the note.

If you set `restrictedToMinimumLevel` on `WriteTo.Map()` rather than on the wrapped sink, this will do what you need.

I don't think it's likely we'll add a configuration option for this in the near future, but it's a good data point to have - thanks again!

**Comment by sorcerb** [comment]
Worked to me:
```
.WriteTo.Map(evt => evt.Level, (level, wt) =>
                    wt.File(
                        $"{Environment.GetEnvironmentVariable("LOGDIR")}\\{DateTime.Now.ToString("yyyy-MM-dd")}\\{Environment.MachineName}-Log-{level}.log",
                        outputTemplate: logFormat, restrictedToMinimumLevel: LogEventLevel.Warning)
            )

```
```
.WriteTo.Map(evt => evt.Level, (level, wt) =>
                    wt.File(
                        $"{Environment.GetEnvironmentVariable("LOGDIR")}\\{DateTime.Now.ToString("yyyy-MM-dd")}\\{Environment.MachineName}-Log-{level}.log",
                        outputTemplate: logFormat), restrictedToMinimumLevel: LogEventLevel.Warning
            )
```
