### ISSUE TITLE
How to dynamic log different file in different dir?

### ISSUE THREAD

**Issue by MiyamuraMiyako** [serilog/serilog-sinks-file#142]
For example:
`Log/ModuleName/Date/ID/ApiName.TXT`
I need this path struct and log filename rules.

**Comment by skomis-mm** [comment]
Hi @MiyamuraMiyako ,

check https://github.com/serilog/serilog-sinks-map

**Comment by MiyamuraMiyako** [comment]
@skomis-mm I try sinks.map, but still not understand how to write log to different dir when condition more than one.

**Comment by skomis-mm** [comment]
@MiyamuraMiyako , there is an overload with `LogEvent` argument, you can build complex key  built on multiple conditions:

```csharp
Log.Logger = new LoggerConfiguration()
        .WriteTo.Map(
        logEvent => new
        {
            ModuleName = logEvent.Properties["ModuleName"].ToString("l", null),
            ID = logEvent.Properties["Id"].ToString()
        },
        (key, lc) => lc.File($"Log/{key.ModuleName}/Date/{key.ID}/ApiName.txt"))
    .CreateLogger();

Log.ForContext("ModuleName", "internal").Information("test {Id}", 42);

Log.CloseAndFlush();
```

**Comment by MiyamuraMiyako** [comment]
@skomis-mm Thanks a lot.
