### ISSUE TITLE
if i wanna delete the file when the serilog is logging on ,what should i set the serilog ?

### ISSUE THREAD

**Issue by hangyejiadao** [serilog/serilog-sinks-file#143]

**Comment by liviriniu** [comment]
This `Issues` channel of discussion is primarily intended to deal with issues of the libraries themselves. For helping users troubleshoot their problems in using/better understand the libraries, stackoverflow.com is much more of help. Be sure to add the `#serilog` tag to your well formed question on stackoverflow.com. This method of separating types of discussions was well thought, this way we all have a better organized environment to help each other. While contributors/members of Serilog projects are very pro support to those in need, we should understand they are making efforts in their spare time / free time and we as users are making their lives easier by staying organized. Using stackoverflow.com many more knowledgeable people will see your problem and chances are that more quickly it can be resolved.

**Comment by bartelink** [comment]
Also a dup of https://github.com/serilog/serilog/issues/1423

**Comment by rafaelsc** [comment]
Did you tried to set up the file sink with ```shared: true``` ?
https://github.com/serilog/serilog-sinks-file#shared-log-files

**Comment by hangyejiadao** [comment]
> Did you tried to set up the file sink with `shared: true` ?
> https://github.com/serilog/serilog-sinks-file#shared-log-files

@rafaelsc  of course i have set up the file sink with shared:true ,but i still cant delete it and open it in  
visual studio

**Comment by rafaelsc** [comment]
Delete a file is not possible now. You can see the issues #96 and #128. 
But open a shared log file should be possible and I never had a problem before. Maybe something in your computer is not allowing that like a antivirus.
But I would suggest to open using notepad++.

**Comment by impr0t** [comment]
It's sad to see that this is still an outstanding issue. Allowing the deletion of the file, and automatically re-creating it seems to be a fairly logical way of going about this. Are there any other methods available to drop the locks?
