### ISSUE TITLE
Infinite loop where fileSizeLimitBytes = 0 and rollOnFileSizeLimit = true

### ISSUE THREAD

**Issue by KorneiDontsov** [serilog/serilog-sinks-file#146]
```csharp
loggerConfiguration.WriteTo.File(
    filePath,
    minLevel,
    outputTemplate,
    fileSizeLimitBytes: 0,
    rollOnFileSizeLimit: true)
```
This code brings an infinite loop at [RollingFileSink.cs:85](https://github.com/serilog/serilog-sinks-file/blob/c2375ebd46f872042b5b68fe763b391f314369e2/src/Serilog.Sinks.File/Sinks/File/RollingFileSink.cs#L85).
`fileSizeLimitBytes` is validated to be non-negative. I believe it should be validated to be positive.

**Comment by cocowalla** [comment]
Hi, thanks for the report! I'll take a look and push a fix shortly!

**Comment by cocowalla** [comment]
Fixed, thanks again for the report!
