### ISSUE TITLE
Include Date in Log file name using app.config

### ISSUE THREAD

**Issue by taren7** [serilog/serilog-sinks-file#148]
Hi,
I am using app.config to set the serilog configuration. Is there a way to append timestamp in the log file name while configuring in xml application configuration. I used the following keys in app.config, but it doesn't work:

add key="serilog:using:File" value="Serilog.Sinks.File"
add key="serilog:write-to:File.path" value="C:\logs\myapp-{Date}.txt"

It will not replace {Date} with current date while saving the file.

**Comment by cocowalla** [comment]
@taren7 I'm afraid your code is missing, would appreciate if you could add it.

**Comment by taren7** [comment]
@cocowalla  i have updated the app.config keys in my query

**Comment by cocowalla** [comment]
The `{Date}` syntax was only used in the now deprecated [serilog-sinks-rollingfile](https://github.com/serilog/serilog-sinks-rollingfile) project - now as long as you specify a rolling interval with `rollingInterval`, a timestamp will automatically be added to the end of the filename.

Using appsetting config, it would look like this:

```xml
<add key="serilog:using:File" value="Serilog.Sinks.File" />
<add key="serilog:write-to:File.path" value="myapp-.txt" />
<add key="serilog:write-to:File.rollingInterval" value="Day" />
```

That would result in filenames like:

```
myapp-20200501.txt
myapp-20200502.txt
myapp-20200503.txt
```

You can see precisely how dates are formatted [here](https://github.com/serilog/serilog-sinks-file/blob/f18cb0e8aaf54a77c85cfd392028c94218888e4c/src/Serilog.Sinks.File/Sinks/File/RollingIntervalExtensions.cs#L21).

**Comment by taren7** [comment]
@cocowalla  Thank you very much. It works seamlessly now.
