### ISSUE TITLE
How to Read logs.json File

### ISSUE THREAD

**Issue by Lucifer-Elf** [serilog/serilog-sinks-file#149]
Hi , I want to read logs.json file with containing below message
```
{"Timestamp":"2020-05-20T22:57:18.7897116+04:00","Level":"Information","MessageTemplate":"{@holder}","Properties":{"holder":{"_typeTag":"LogRecord","LogId":123,"LogLevelId":3,"Message":"test","FunctionName":"main1","LogLevel":"INFORMATION"},"MachineName":"test-paul33","ProcessId":27568,"ThreadId":1}}

{"Timestamp":"2020-05-20T22:57:18.8425772+04:00","Level":"Information","MessageTemplate":"{@holder}","Properties":{"holder":{"_typeTag":"LogRecord","LogId":123,"LogLevelId":3,"Message":"test","FunctionName":"main","LogLevel":"INFORMATION"},"MachineName":"test-paul33","ProcessId":27568,"ThreadId":1}}
```

read it create JSON object or structure send data to elastic search.
yes! we can use the sink directly to send data. but currently, I have a booting phase where I log everything in the file and close serilog. then i send everything to elastic search and open new serilog with elastic search configuration.

**Comment by cocowalla** [comment]
Hi! I gather you want to send JSON logs written by Serilog to Elasticsearch, but I'm afraid I'm not sure exactly what it is you are asking?

**Comment by nblumhardt** [comment]
If you write the files using _Serilog.Formatting.Compact_, you can read them back into `LogEvent`s with _Serilog.Formatting.Compact.Reader_ and pass those back through Serilog's `ILogger.Write()`. HTH!
