### ISSUE TITLE
Logs are not written to a file after restarting IIS 

### ISSUE THREAD

**Issue by Andrei-Astakhov** [serilog/serilog-sinks-file#150]
Hello,
I spent a lot of time before I opened this issue but I didn't find a solution. Hope you can help me.
I have read the following article:
[https://nblumhardt.com/2014/05/logging-and-locked-files/](https://nblumhardt.com/2014/05/logging-and-locked-files/) and the following issue:
[https://github.com/serilog/serilog/issues/1240](https://github.com/serilog/serilog/issues/1240) but they didn't help me.

The problem is that each time IIS is restarted the logs are not written. For example, if the current log file name is **20200521.slog** and I restart IIS, I don't see new logs. However, if I just restart the web site the next day, so the new file name should be **20200522.slog**, everything works.
The logs have the Day rolling interval. The log folders are **D:\Logs\MySite\Event** and **D:\Logs\MySite\Error**. The **MySite** folder grants full control to the user under whose permissions the web site app pool is started and also the **IUSR** and **IIS_IUSRS** groups have full control to the folder.
Here is my Serilog configuration

    Log.Logger = new LoggerConfiguration()
        .Enrich.WithUTCDate()
        .Enrich.WithThreadId()
        .Enrich.WithThreadName()
        .Enrich.WithErrorId()
        .WriteTo.File(
            path: ConfigurationManager.AppSettings["SerilogEventPath"],
            outputTemplate: "{NewLine}{UTCDate}\t{ThreadId}\t{ThreadName}\t{ErrorId}{NewLine}{Message:l}{NewLine}{Exception}{NewLine}",
            rollingInterval: RollingInterval.Day)
        .WriteTo.File(
            path: ConfigurationManager.AppSettings["SerilogErrorPath"],
            restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Error,
            outputTemplate: "{NewLine}{UTCDate}\t{ThreadId}\t{ThreadName}\t{ErrorId}{NewLine}{Message:l}{NewLine}{Exception}{NewLine}",
            rollingInterval: RollingInterval.Day)
        .Enrich.WithAppName()
        .Enrich.WithHostName()
        .Enrich.WithLogOwner()
        .Enrich.WithType()
        .WriteTo.DurableHttpUsingFileSizeRolledBuffers(
            requestUri: ConfigurationManager.AppSettings["SerilogRequestUri"],
            bufferBaseFileName: ConfigurationManager.AppSettings["SerilogBufferBaseFileName"],
            httpClient: new LogstashHttpClient(),
            textFormatter: new LogstashJsonFormatter(),
            batchFormatter: new ArrayBatchFormatter()
        )
        .CreateLogger();

I have also tried to set the **shared** option to true but without success. Can you explain whether my configuration is the cause of the problem and if there is a way to fix this problem.
Thank you,
Andrei.

**Comment by cocowalla** [comment]
Hi! Could you please try enabling Serilog's [internal diagnostic logging] (https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) and see if you see anything relevant? (ensuring SelfLog is configured to write somewhere you will see even if the file in question isn't updated!)

**Comment by Andrei-Astakhov** [comment]
Hi!
Thank you for your suggestion. I have added the internal diagnostic to my site, but there are no any errors in the internal log. I dug deeper and found the strange behavior.

First, let's me explain my scenario in greater detail. By the fact, I set the **path** option for the sink as a relative path. E.g. **..\\..\Logs\MySite\Event**. My site is placed on the D drive in the following path: **D:\Apps\Sites\MySite**. So I guess that logs should be placed in the **D:\Apps\Logs\MySite\Event**. This is so when I deploy my site to the mentioned folder. However, when I restarted IIS, logs are written to the **C:\Windows\Logs\MySite\Event** folder.
This is not the expected behavior. 

Even though I found a solution to this problem by using absolute paths, it would be great if you will confirm that the issue doesn't relate to Serilog and the problem is in IIS.
Thanks.

**Comment by cocowalla** [comment]
It certainly looks like this is an IIS issue - if you use a relative path, the logs will be relative to the process that does the writing, which presumably is varying here, perhaps between master and worker processes.

If you don't want to use an absolute path, you also have the option of using an environment variable.

Thanks for digging in and finding the root cause, this is the kind of thing we're likely to see again, so it's great to have the knowledge here!

**Comment by esskar** [comment]
I am having a hard time with relative paths. As mentioned, it will point to the location where the w3wp.exe is located. is there a  way to use  `AppDomain.CurrentDomain.BaseDirectory` as the base directory?

**Comment by cocowalla** [comment]
Only if you configure the logger programmatically.

Otherwise, you also have the option of using environment variables in config files. For example:

```
%PROGRAMDATA%\MyApp\Logs
```

This is one of Windows' built-in env vars, but of course, you can setup your own to point anywhere.
