### ISSUE TITLE
Log file not being created when running in Docker container

### ISSUE THREAD

**Issue by jlat96** [serilog/serilog-sinks-file#151]
When debugging .net core 3.1 locally outside of a container on windows my log file is being created as expected in the directory C:/logs/api. When I build the application into a Docker container, I would expect to see the directory /logs to be created inside the container but it is not. Additionally I do not see any console output when I attach to the container.

My appsettings.Development.json file:
```cs
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information",
        "System": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "File",
        "args": {
          "path": "/logs/api/api-log-.log",
          "rollingInterval": 3,
        }
      }
    ]
  }
}
```

my Dockerfile

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

COPY . .
RUN echo Building REST API for $ENV
RUN if [ "$ENV" = "development" ] ; \
	then dotnet build -c Debug -o out /p:EnvironmentName=Development;  \
	else dotnet build -c Release -o out; \
	fi

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
EXPOSE 80
EXPOSE 443
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "MyApp.dll"]
```

I can confirm that the ASPNETCORE_ENVIRONMENT variable is being set to Development in the web.config from within the container. Am I missing something that would create the log directory on the linux container?

**Comment by cocowalla** [comment]
It looks like you are not pre-creating the `/logs/api` folder in your Dockerfile - could it be that the user in the container doesn't have access to create it at runtime?

**Comment by jlat96** [comment]
@cocowalla I just tried to create the directories in my Dockerfile

```dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
EXPOSE 80
EXPOSE 443
WORKDIR /app
COPY --from=build /app/out .
RUN mkdir -p /logs/api
ENTRYPOINT ["dotnet", "MyApp.dll"]
```

The directories are there but the file is still not being written. Just to be sure I verified that I have write permission as a non sudo user and I can create files.

**Comment by cocowalla** [comment]
Could you please try enabling Serilog's [internal diagnostic logging](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics), configuring it to write to standard output, and see if you see anything relevant?

This should most likely provide an insight into the underlying problem.

**Comment by jlat96** [comment]
I enabled this but am still seeing no output. I do not see the SelfLog output locally outside of the container either.

Maybe something wrong with my config?

```cs
Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .CreateLogger();

            Serilog.Debugging.SelfLog.Enable(Console.Out);
```

**Comment by cocowalla** [comment]
When you say you don't see the SelfLog output, have you started the container in interactive mode so you can see console output, or alternatively are you checking `docker logs` to look for the output?

If you are doing either of those and still don't see any output, it would be really helpful if you could put together a small repro; you provided your Dockerfile already, but a simple console app that does nothing but try and fail to log to the path in question would be really useful 👍

**Comment by jlat96** [comment]
@cocowalla Thank you for your help. This ended up being a problem with by build configuration not correctly building the development environment into the container
