### ISSUE TITLE
Why it is plannned to make the FileSink constructor internal?

### ISSUE THREAD

**Issue by pepelev** [serilog/serilog-sinks-file#153]
Making constructor public provides users with the additional flexibility over `FileSink` usage and lifetime. If one able to create `FileSink` and assign it to variable, then one also able to pass that sink to several `LoggerConfiguration`s. This approach allows to reuse same `FileStream` without operating system's sharing.

Another way that a public constructor can give flexibility is as follows. Say a developer wants to provide users with the ability to change the log path during application runtime. Thus, developer may implement something similar (suppose for brevity, `FileSink` has constructor overload with single string parameter):

```
public sealed class ExchangeableSink : ILogEventSink
{
    private ILogEventSink currentSink;

    public ExchangeableSink(ILogEventSink startSink)
    {
        currentSink = startSink;
    }

    public void Emit(LogEvent logEvent)
    {
        currentSink.Emit(logEvent);
    }

    public ILogEventSink Exchange(ILogEventSink newSink)
    {
        var oldSink = Interlocked.Exchange(ref currentSink, newSink);
        return oldSink;
    }
}

static void Main()
{
    var sink = new ExchangeableSink(
        new FileSink("log.txt")
    );

    using var log = new LoggerConfiguration()
        .WriteTo.Sink(sink)
        .CreateLogger();

    log.Information("Hello world to log.txt");

    var oldSink = sink.Exchange(new FileSink("new-log.txt"));
    (oldSink as IDisposable).Dispose();

    log.Information("Hello world to new-log.txt");
}
```

There are many other situations that can take advantage of the public `FileSink` constructor (and other sinks).

**Comment by skomis-mm** [comment]
Hi @pepelev , 

I believe this design for many Serilog sinks is to reduce maintenance costs and allow future modifications without breaking changes, providing only public surface via extension methods.

There are a couple of extension points. One is [file hooks](https://github.com/serilog/serilog-sinks-file#extensibility), specific to file sink. Another one is [LoggerSinkConfiguration.Wrap(..)](https://github.com/serilog/serilog/pull/955) method, which allows decoration over another sink. 

Using the second one you can actualy can get a reference to any sink instance.
 
```csharp
public static class SerilogHelper
{
    public static ILogEventSink DangerousGetSink(Action<LoggerSinkConfiguration> configAction)
    {
        ILogEventSink captured = null;
        LoggerSinkConfiguration.Wrap(new LoggerConfiguration().WriteTo, inner => captured = inner, configAction, default, default);
        return captured;
    }
}
```

usage:
```csharp
var file1 = SerilogHelper.DangerousGetSink(s => s.File("C:/temp/out1.log"));
var file2 = SerilogHelper.DangerousGetSink(s => s.File("C:/temp/out2.log"));

var es = new ExchangeableSink(file1);

using var logger = new LoggerConfiguration()
    .WriteTo.Sink(es)
    .CreateLogger();
    
logger.Information("one");
(es.Exchange(file2) as IDisposable)?.Dispose();
logger.Information("two");
```

**Comment by pepelev** [comment]
Hi @skomis-mm, thank you for your response!

Approach you shown is a bit fragile, because when delegate passed to a method, caller can't be sure, that delegate being called. It also uses the `Wrap` method, I suppose, not as intended.

When constuctors are internal, i can't place something between, say, `PeriodicFlushToDiskSink` and `FileSink` i.e. write like that
```
new PeriodicFlushToDiskSink(
    new FlushNotifyingSink(
        new FileSink(
            "log.txt"
        ),
        () => Console.WriteLine("Flush occured!")
    ),
    flushInterval
)
```

Could you please tell me how public extension methods and internal constructors reduce maintenance costs. It isn't clear for me.

**Comment by skomis-mm** [comment]
@pepelev ,

> Approach you shown is a bit fragile, because when delegate passed to a method, caller can't be sure, that delegate being called. It also uses the Wrap method, I suppose, not as intended.

That's true, this method was designed for other purpose. The implementation can be changed, but practically, for behavior changes Serilog tries to be compatible too once the behavior is introduced, unless it is a clear bug. 

```csharp
new PeriodicFlushToDiskSink(
    new FlushNotifyingSink(
        new FileSink(
            "log.txt"
        ),
        () => Console.WriteLine("Flush occured!")
    ),
    flushInterval
)
```
This wouldn't work anyway, since `PeriodicFlushToDiskSink` doesn't provide a hook when the sink is about to flush. It is an implementation detail of the FileSink with narrow goal and I beleive that's why the type itself was internalized, not just the construction. For such scenario I would implement this sink from the scratch (or copied the source code) and implemented decoration via `Wrap(..)` method.

> Could you please tell me how public extension methods and internal constructors reduce maintenance costs. It isn't clear for me.

 If new parameter is added, it couldn't be added to the same constructor without breaking change, the new overload is introduced. It gets more complicated if there are parameters with default values. When there are many of them, like for FileSink its turn to a mess to support backward compat. And constructor parameters not necessary maps 1-to-1 with configuration extension method parameters.

**Comment by pepelev** [comment]
@skomis-mm, thanks for your answers.

> This wouldn't work anyway, since `PeriodicFlushToDiskSink` doesn't provide a hook when the sink is about to flush. It is an implementation detail of the FileSink without extension points and I believe that's why the type itself was internalized, not just the construction.

It will work, i will show you! There is no need any explicit hook for that. It can be implemented in a native way.

```
public sealed class FlushNotifyingSink : ILogEventSink, IFlushableFileSink
{
    private readonly IFlushableFileSink flushableSink;
    private readonly Action notification;
    private readonly ILogEventSink sink;

    public FlushNotifyingSink(ILogEventSink sink, Action notification)
    {
        this.sink = sink;
        flushableSink = sink as IFlushableFileSink;
        this.notification = notification;
    }

    public void FlushToDisk()
    {
        if (flushableSink != null)
        {
            flushableSink.FlushToDisk();
            notification();
        }
    }

    public void Emit(LogEvent logEvent)
    {
        sink.Emit(logEvent);
    }
}

static void Main()
{
    var sink = new PeriodicFlushToDiskSink(
        new FlushNotifyingSink(
            new FileSink(
                "log.txt",
                new MessageTemplateTextFormatter("{Message}{NewLine}"),
                null
            ),
            () => Console.WriteLine("Flush occured!")
        ),
        TimeSpan.FromSeconds(1)
    );
    using var log = new LoggerConfiguration().WriteTo.Sink(sink).CreateLogger();


    for (var i = 0;; i++)
    {
        log.Information($"Hello {i}");
        Thread.Sleep(100);
    }
}
```

This uses a native extension point and works perfectly fine for me.


> If new parameter is added, it couldn't be added to the same constructor without breaking change, the new overload is introduced. It gets more complicated if there are parameters with default values. When there are many of them, like for FileSink its turn to a mess to support backward compat. And constructor parameters not necessary maps 1-to-1 with configuration extension method parameters.

It, as i understand, has no difference with extension method except flexible mapping of parameters. If i am right, same maintenance problems appear when modifications are made to any of `FileLoggerConfigurationExtensions.File` extension method overloads.

In my opinion, such backward compatibility problems are easier to solve at class level, due to reduced context. For providing new functionality new classses may be introduced. That modification does not cause backward compatibility issues.

**Comment by skomis-mm** [comment]
@pepelev , now I see

> This uses a native extension point and works perfectly fine for me.

 Right, great 👍. In this particular case it seems there is no reliable without building your own `PeriodicFlushToDiskSink`.

> It, as i understand, has no difference with extension method except flexible mapping of parameters. If i am right, same maintenance problems appear when modifications are made to any of FileLoggerConfigurationExtensions.File extension method overloads.

It is. At least, it is a single set. New classes for added features already exist (SharedFileSink, RollingFileSink), they are internal and have more room for change. 

There is [serilog-sink-rollingfile](https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/RollingFileSink.cs) package that is in maintenance mode with public `RollingFileSink` type and public constructor. If it would be internal seems it could reuse rolling implementation from this package.

From my experience Serilog keeps compatibility bar very high and file sink constructors can survive longer that it seems (they were obsoleted 14 months ago). So if there is a real need I wouldn't hesitate to use them to get the job done.

**Comment by pepelev** [comment]
@skomis-mm thank you for your great answers. I see no reason to leave this question open. So i close it.
