### ISSUE TITLE
Calling Log.CloseAndFlush causing object disposed exceptions on log

### ISSUE THREAD

**Issue by worldleaderpretend** [serilog/serilog-sinks-file#155]
Reviewing the other parts of the Serilog code, I was under the assumption that log.Debug() etc should never throw exceptions.

The rolling file sink will do so if the sink is disposed by Log.CloseAndFlush. I have several loggers derived from the root logger, and to make the check for all of these would require locks and other expensive operations to manage. Yes, CloseAndFlush() isn't something that is called often, but there should be a mechanism to recover if this is called more than once, and if it is called more than once than the consumer will need to use locking to avoid a race condition.

I believe that was the original purpose of the SilentLogger:

        public static void CloseAndFlush()
        {
            var logger = Interlocked.Exchange(ref _logger, SilentLogger.Instance);

            (logger as IDisposable)?.Dispose();
        }
was so new instances do not suffer from a closed sink. Unfortunately this does not propagate to any derived loggers.

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. Can you please include an exception stack trace showing the exception you've experienced? Thanks!

**Comment by russellfoster** [comment]
The exception I get is the ObjectDisposedException thrown in the Emit()

        public void Emit(LogEvent logEvent)
        {
            if (logEvent == null) throw new ArgumentNullException(nameof(logEvent));

            lock (_syncRoot)
            {
                if (_isDisposed) throw new ObjectDisposedException("The log file has been disposed.");

                var now = Clock.DateTimeNow;
                AlignCurrentFileTo(now);

                while (_currentFile?.EmitOrOverflow(logEvent) == false && _rollOnFileSizeLimit)
                {
                    AlignCurrentFileTo(now, nextSequence: true);
                }
            }
        }

I see there is also the chance for a ArgNullException but this is probably an internal check. Although I would prefer a log routine with zero chance of exceptions. Maybe the answer is to wrap Emits and then notify exceptions via the Self logger?

Very nice project! Coming over from log4net and see you all have done a fantastic job!

**Comment by nblumhardt** [comment]
Thanks for the reply - these exceptions should already be caught and sent to `SelfLog` - is it possible to grab a stack trace from your top-level exception handler? Thanks :+1:

**Comment by russellfoster** [comment]
Apologizes all around. It seems I was capturing first chance exceptions and mistaking them for unhandled ones. Thanks for helping out!

**Comment by nblumhardt** [comment]
👍
