### ISSUE TITLE
new log per process in appsetting.json

### ISSUE THREAD

**Issue by maheshenator** [serilog/serilog-sinks-file#156]
I use this config setting. And it is common config for all my exe in the solution(WPF). Wanted to have the properties configurable externally, Is there any way I can update file name alone in Code, and use rest of the properties as such, including log folder from the appsetting.json file? 
Objective: shared property is not working, ie, multiple exes are not able to log the information in same file. So, wanted to have new file per instance of application. And also dont want to leave all setting in code.

"Name": "File",
        "Args": {
          "path": "%userprofile%\\MyAppLogs\\AppStructuredLog-.json",
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "fileSizeLimitBytes": 512000,
          "retainedFileCountLimit": 100,
          "rollingInterval": "Day",
          "rollOnFileSizeLimit": "true",
          "shared": true
        }

**Comment by nblumhardt** [comment]
Hi! Thanks for getting in touch. There's no plan to add this functionality at present, but you should be able to use _Microsoft.Extensions.Configuration_ to change a single setting from code, though it may take some experimentation.
