### ISSUE TITLE
File Never Created when using BlazorWA app

### ISSUE THREAD

**Issue by markiemarkus** [serilog/serilog-sinks-file#158]
I have ensured my Blazor app contains
           ` builder.Logging.AddSerilog();`

My app logs to the console using the 
However when including that it should write to file in addition to the console or into a file in it's entirety the file is never created.
I have attempted three basic variations of setting this up.

```
 var levelSwitch = new LoggingLevelSwitch
            {
                MinimumLevel = Serilog.Events.LogEventLevel.Debug
            };

```
with
```
Log.Logger = new LoggerConfiguration().MinimumLevel.ControlledBy(levelSwitch)
                        .Enrich.FromLogContext()
                        .WriteTo.File(@"C:\test\log.txt")
                        .CreateLogger();
```
or
```
            Log.Logger = new LoggerConfiguration()
       .Enrich.FromLogContext()
       .WriteTo.BrowserConsole()
       .WriteTo.File(@"C:\test\log.txt")
       .CreateLogger();
```

or
```

   Log.Logger = new LoggerConfiguration()
                 .MinimumLevel.ControlledBy(levelSwitch)
                 .Enrich.WithProperty("InstanceId", Guid.NewGuid().ToString("n"))
                 .WriteTo.BrowserConsole()
                 .WriteTo.File(@"log.txt", outputTemplate: "{Timestamp:o} [{Level:u3}] [{Properties:j}] {Message:lj}{NewLine}{Exception}",
                 rollingInterval: RollingInterval.Day,
                 retainedFileCountLimit: 40, rollOnFileSizeLimit: true, fileSizeLimitBytes: 10000000)
                 .CreateLogger();
```

**Comment by cocowalla** [comment]
I'm not actually familiar with Blazor, but I would have presumed that Web Assembly runs in a sandbox, and wouldn't be able to write arbitrary files on the host's disk?

**Comment by GerkinDev** [comment]
I don't think this sink should work on WASM, since it requires access to the file system. I've used in place https://github.com/nblumhardt/serilog-sinks-browserhttp with https://www.nuget.org/packages/Serilog.AspNetCore.Ingestion/ for end-to-end logging: serilog in blazor client send requests to the server's ingest endpoint, that write those logs in a separate file via filters
