### ISSUE TITLE
Method not found: `Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File...`

### ISSUE THREAD

**Issue by bcanzanella** [serilog/serilog-sinks-file#159]
I'm having an intermittent problem where I run into this exception at runtime:

```

{"Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(
Serilog.Configuration.LoggerSinkConfiguration, 
Serilog.Formatting.ITextFormatter, 
System.String, Serilog.Events.LogEventLevel, 
System.Nullable`1<Int64>, 
Serilog.Core.LoggingLevelSwitch, 
Boolean, 
Boolean, 
System.Nullable`1<System.TimeSpan>, 
Serilog.RollingInterval,
Boolean, 
System.Nullable`1<Int32>, 
System.Text.Encoding, 
Serilog.Sinks.File.FileLifecycleHooks)'."}

```

I'm not really sure if this is an issue with serilog-sinks-file _per se_, I'm just throwing this out there in the hope anyone has any ideas...

I've seen some other related issues (like https://github.com/serilog/serilog-sinks-seq/issues/95) that seem to point to a versioning issue with `System.Net.Http`, I'm trying to take that out of the equation, though there's nothing really pointing to it. AFAICT serilog-sinks-file doesn't even have a direct dependency on `System.Net.Http`...

At runtime, I can check the diagnostic build output of the last build for any version mismatches. There aren't any statements including the text `was chosen because it was primary` related to `System.Net.Http`.

package.config:
```
<package id="Serilog" version="2.8.0" targetFramework="net472" />
  <package id="Serilog.Enrichers.Process" version="2.0.1" targetFramework="net472" />
  <package id="Serilog.Enrichers.Thread" version="3.1.0" targetFramework="net472" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net472" />
  <package id="SerilogTimings" version="2.2.0" targetFramework="net472" />
```

This is happening in a Visual Studio extension I'm developing, and what might make it more problematic, is that my extension targets both VS 2017 and VS 2019. I believe VS 2017 is what introduced System.Net.Http version 4.2.0.0, which, i think, is the only place that version has ever existed (https://stackoverflow.com/questions/47570912/strange-issue-with-system-net-http-4-2-0-0-not-found). 
I've tried bindingRedirects, using the nuget version of `System.Net.Http`, using `<Reference Include="System.Net.Http" />` and various combinations with that... and I'm really not sure what to do. This seems to happen for about 40% of the builds I run, and when it doesn, I don't have any logging... I'm throwing this out here as a long shot!

**Comment by cocowalla** [comment]
Hmm, odd it's only happening sometimes! It sounds like it might be a tooling issue. Have you tried totally deleting the output dir before building (IME the "clean" command can still leave some cruft lying around sometimes)? Also might be worth nuking your local NuGet cache.

**Comment by bcanzanella** [comment]
Thanks for the tip @cocowalla I tried that with no luck (but now I have a cool new super cleaner powershell script!). 

But... what you said about a `tooling issue` got me thinking...

Since that `FileLoggerConfigurationExtensions.File` extension wasn't found, I wrote my own just to test that it was working, something like : 

```
public static LoggerConfiguration CustomFile(
			 this LoggerSinkConfiguration sinkConfiguration,
			 ITextFormatter formatter,
			 string path,
			 LogEventLevel restrictedToMinimumLevel = LogEventLevel.Verbose,
			 long? fileSizeLimitBytes = 1073741824,
			 LoggingLevelSwitch levelSwitch = null,
			 bool buffered = false,
			 bool shared = false,
			 TimeSpan? flushToDiskInterval = null,
			 RollingInterval rollingInterval = RollingInterval.Infinite,
			 bool rollOnFileSizeLimit = false,
			 int? retainedFileCountLimit = 31,
			 Encoding encoding = null)	{			
			var addSink = new Func<ILogEventSink, LogEventLevel, LoggingLevelSwitch, LoggerConfiguration>(sinkConfiguration.Sink);
			// this ctor is obsolete... aka this is all testing code... don't do this...
			var sink = new SharedFileSink(path, formatter, fileSizeLimitBytes, encoding);
			return addSink(sink, restrictedToMinimumLevel, levelSwitch);
		}
```
and then _that_ threw another exception, something like: `Could not find type RollingInterval`... what now???? I know that's in the 4.0 release... ok, so at runtime, it isn't using that dll version... 

Since I'm developing an extension for Visual Studio, I can see all the assemblies at runtime and that's where I finally found the issue... 

![image](https://user-images.githubusercontent.com/834948/86282839-f7d6b080-bbad-11ea-8cdf-b72654fbcd35.png)

I also have the GitHub for Visual Studio extension installed and it also uses Serilog & Serilog.Sinks.File, but it's using the 3.X version of Serilog.Sinks.File (one without that extension method I was using, as well as not having the `RollingInterval` type). 

Whichever plugin loads first "wins" and that explains why i wouldn't always see this! I don't have a great solution except to lock down my versions to match what GH uses, but at least there's an explanation!

**Comment by cocowalla** [comment]
Great find, and some super detective work 🕵️, really appreciate you writing up the resolution!
