### ISSUE TITLE
How to add Time offsets in timestamp

### ISSUE THREAD

**Issue by jarDotNet** [serilog/serilog-sinks-file#160]
When I create a log file the output is in ISO 8601 UTC local time format, but when I create the same log outputs using Windows Event Viewer (EventLog) or Seq, I get my current local time with the corresponding time offset (+2).

How can I get this same Time offset result in my file outputs as I get using EventLog or Seg?

Thanks in advance,
JarDorNet.

**Comment by cocowalla** [comment]
If I understand correctly, you are currently writing UTC timestamps in your log files with Serilog.Sinks.File, but you want to write local time with an offset instead?

You can do this by [formatting](https://github.com/serilog/serilog/wiki/Formatting-Output) the `Timestamp` message template token, for example:

```json
"outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {Level} {ThreadId} [{SourceContext:l}] {Message:l}{NewLine}{Exception}"

Note the `zzz`, which means "UTC offset".
```

**Comment by jarDotNet** [comment]
Right! That's the question and that must be the correct answer.

But if I add the suggested template, then I get a classic Console output:

`2020-07-02 13:58:44.209 +02:00  WRN [SampleRepository 12] Warning from SampleRepository.GetAll()`

So the real problem must be with the `CompactJsonFormatter`, because if I set `JsonFormatter` instead (and without defining any output template) I get the correct format, as `zzz` is just defined in the default output template.

Any idea about what should be the incompatibility problem here?

Thanks again,
JarDotNet.

**Comment by cocowalla** [comment]
Ah! So I think then you want the opposite of what I suggested - you want to see ISO 8601 times like `2020-07-02 13:19:09Z` in your log files?

You can do this using the `u` format string:

```json
"outputTemplate": "{Timestamp:u} {Level} {ThreadId} [{SourceContext:l}] {Message:l}{NewLine}{Exception}"
```

**Comment by jarDotNet** [comment]
Nope,

No way this time, both with `CompactJsonFormatter` and `JsonFormatter`. With the new output template, I get the same Console like output in both cases.

I think the real problem must be with `CompactJsonFormatter` as I stated, because with the `JsonFormatter` (and without no output template configuration) I get my local GTM+2 timestamp output as expected.

As a test case, this is my current Serilog configuration:

```
  {
    "Name": "File",
    "Args": {
      "path": "./logs/SharCommLog-.json",
      "fileSizeLimitBytes": "524288",
      "rollingInterval": "Day",
      "rollOnFileSizeLimit": "true",
      "retainedFileCountLimit": "10",
      "shared": "true",
      //"formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
      "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
      //"outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {MessageTemplate} {Level:u3} [{SourceContext:l} {ThreadId}] {Message:l}{NewLine}{Exception}",
      "restrictedToMinimumLevel": "Warning"
    }
  }
```

So I can get my problem solved using `JsonFormatter`, but not in a compact Json output format.

Thnk you again,
JarDotNet.

**Comment by cocowalla** [comment]
Just so things can be totally clear for me, what you want is local time with a UTC offset, when using `CompactJsonFormatter`?

E.g. `2020-07-02 13:58:44.209 +02:00`

**Comment by jarDotNet** [comment]
That's right.

When I create a log using EventLog or Seq f.e., I get a correct output like that:

`03 Jul 2020 08:37:28.963`

But with File I get this other output:

`"@t":"2020-07-03T06:37:28.9631790Z"`

I thought the problem would be with File sink, but thanks to your suggestions I have been able to see that the real problem was due to `CompactJsonFormatter`. So if I set `JsonFormatter` instead, I get a correct output again, but not in a compact Json format this time:

`"Timestamp":"2020-07-03T08:37:28.9631790+02:00"`

So maybe I should move my issue to the "CompactJsonFormatter" git repository instead.

**Comment by nblumhardt** [comment]
Hi @jarDotNet ! Thanks for the follow-up. This is by design in `CompactJsonFormatter` - it always uses UTC time. If you are keen to override that default, however, the code for `CompactJsonFormatter` itself is only a few lines and is easy to copy/modify. (We've deliberately avoided adding a lot of configurability there, to keep this option viable.) HTH!

**Comment by jarDotNet** [comment]
Hi @nblumhardt, and thanks for the clarification.

I think we will use `JsonFormatter ` at this time, and take into consideration your suggestion for a more advanced phase of our development.

Thanks u all!
