### ISSUE TITLE
Add support C# 8 nullable reference types

### ISSUE THREAD

**Issue by rafaelsc** [serilog/serilog-sinks-file#165]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netstandard2.1. **NEW**
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Describe the solution you'd like**
Enable [nullable-references](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) in Serilog and add update the codebase to support the nullable reference types in .NET Core 3.0 and 3.1.

**Additional context**
Links about the *Nullable reference types *:
 - [Nullable reference types (C# reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types)
 - [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
 - [Introducing Nullable Reference Types in C#](https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/)

**Comment by Numpsy** [comment]
A small Q. with regards to #139 and the netstandard2.1 project change:

![image](https://user-images.githubusercontent.com/1178570/88783214-69daef00-d186-11ea-9c29-490a3f7b4a14.png)

Could the dependencies be reduced in the 2.1 target, even if the existing 2.0 target is left the same?

**Comment by Numpsy** [comment]
/meant to put that comment in the PR :-(

**Comment by rafaelsc** [comment]
I had a quick look and look like none of this `PackageReference `are **required** for any netstandard _(even the netstandard1.3)_.
I will test more asap and probably create a new PR if we can clean up this `PackageReference`

**Comment by rafaelsc** [comment]
Just created a new PR #172 to remove unnecessary references in the project.
