### ISSUE TITLE
Why Directory.GetCurrentDirectory method was used?

### ISSUE THREAD

**Issue by chucklu** [serilog/serilog-sinks-file#171]
https://github.com/serilog/serilog-sinks-file/blob/5b52dd29f0547b2c5a11caa4f6488d9de6d77683/src/Serilog.Sinks.File/Sinks/File/PathRoller.cs#L44
You might check [What is the difference between these ways of getting current directory?](https://stackoverflow.com/questions/18727692/what-is-the-difference-between-these-ways-of-getting-current-directory)

**Comment by nblumhardt** [comment]
Hi! The behavior here is intentional; it's likely only one way was supported when we ported this to `netstandard1.0`, way back.

**Comment by esskar** [comment]
shouldn't be `AppDomain.CurrentDomain.BaseDirectory`?
