### ISSUE TITLE
provide restrictedToMaximumLevel parameter

### ISSUE THREAD

**Issue by hiwjcn** [serilog/serilog-sinks-file#176]
separate logs with diff log levels into diff log files

- app.info.log
- app.error.log

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-sinks-map is what you're looking for, here 👍

**Comment by hiwjcn** [comment]
@nblumhardt thanks for reply!
but sinks-map wont be my choice.
im using microsoft.extension.logging integrated with serilog.
and dont want to be aware of any serilog features.
just log.information("any thing") is good for me

**Comment by nblumhardt** [comment]
Thanks for the reply, @hiwjcn! _Map_ doesn't require any change to logging calls - it plugs in wherever you configure Serilog, and works behind the scenes.

(Did you mean to post this in https://github.com/serilog/serilog-extensions-logging-file perhaps?)

**Comment by hiwjcn** [comment]
yes im using serilog-extensions-logging-file,and it works well.
the problem is i can't specific maximum log level with file-sink

when using sinks-map , a placeholder is required to make sinks-map take effect,this will force me to modify my codes
and i can't put a log level placeholder every time
``` c#
Log.Logger = new LoggerConfiguration()
    .WriteTo.Map("Name", "Other", (name, wt) => wt.File($"./logs/log-{name}.txt"))
    .CreateLogger();

Log.Information("Hello, {Name}!", "Alice");
// -> Event written to log-Alice.txt

Log.Information("Hello, {Name}!", "Bob");
// -> Event written to log-Bob.txt

Log.Information("Shutting down");
// -> Event written to log-Other.txt

Log.CloseAndFlush();
```

**Comment by nblumhardt** [comment]
`Map()` has a few overloads, you can use the level to generate the filename, there's no need for a special property etc. --- it's very commonly used to implement exactly the scenario you have described, hopefully there's a sample out there.

**Comment by hiwjcn** [comment]
@nblumhardt thank you!
