### ISSUE TITLE
Detected package downgrade: System.IO from 4.3.0 to 4.1.0.

### ISSUE THREAD

**Issue by Yaz-X** [serilog/serilog-sinks-file#177]
Hello,

i'm getting this error when publishing Website (Asp.net Core Version 3.1.8):

Detected package downgrade: System.IO from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.
Serilog.Sinks.File 4.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO (>= 4.3.0)
Serilog.Sinks.File 4.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO (>= 4.1.0)

**Comment by Numpsy** [comment]
For .NET Core 3.x builds I think that should be fixed in the pre-release packages (see #139 and #172) as the references to the System packages are removed in Core 3.0 targets.

Otherwise, does adding a System.IO reference to the website avoid/fix the error?

**Comment by Yaz-X** [comment]
Sorry for not updating this post, Yes i had to add the references with the correct versions for it to publish successfully as a workaround.

**Comment by Mgamerz** [comment]
Was having this exact issue. Updating the file plugin to 5.0 pre-release fixed it. I didn't update the main Serilog though, not sure if that matters.

**Comment by Rogardo** [comment]
I have the same issue in my WPF project for .net5. I must add these lines to my csproj file to make it work.

    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Handles" Version="4.3.0" />

**Comment by nblumhardt** [comment]
I believe this is fixed on the newest 5.0 dev versions. Will ship an RTM shortly.

**Comment by nblumhardt** [comment]
(see also #166, #210)

**Comment by Joren-Thijs-KasparSolutions** [comment]
We just ran into this on .net 7 using the new container publish task. No other projects are affected and all our nuget packages refernce the same version. We fixed it by including this in our packagereferences

https://github.com/dotnet/sdk/issues/3044#issuecomment-476795447

**Comment by nblumhardt** [comment]
It might be time to nudge the minimum framework version targets for this (and Serilog) forwards. Reopening, though I don't think the change will be made here until the upstream Serilog 3.0 happens. Thanks for leaving a note 👍

**Comment by nblumhardt** [comment]
@bartelink guess it's time to bump `dev` in `serilog/serilog` to 4.0, and get started on all of this :-) ... I'll do that today :+1:

**Comment by AraHaan** [comment]
There is a way to fix this without needing to push a new package with ``Directory.Packages.props`` to host all the packages and using Central Package Management to override the version of System.IO that is used by Serilog.

**Comment by nblumhardt** [comment]
Serilog 4.x should no longer suffer from this issue, closing again - and thanks everyone for your input 👍
