### ISSUE TITLE
.NET Core Project, 'shared: true', "System.Diagnostics.Process.Start(LogFile)" Fails: "The process cannot access the file because it is being used by another process."

### ISSUE THREAD

**Issue by onicon-bschaefer** [serilog/serilog-sinks-file#178]
**Serilog Versions:**
```
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Exceptions" Version="5.6.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
```

**.Net Framework 4.8:**
```
<TargetFramework>net48</TargetFramework>
```

**.Net Core 3.1:**
```
<TargetFramework>netcoreapp3.1</TargetFramework>
```

Logger Configuration:
```
        public void ConfigureSerilog()
        {
            string Function = System.Reflection.MethodBase.GetCurrentMethod().Name;
            try
            {
                Log.Logger = new LoggerConfiguration()
                    .MinimumLevel.Debug()
                    .Enrich.WithExceptionDetails()
                    .WriteTo.Console()
                    .WriteTo.File
                    (
                        GetApplicationLogFilePath(),
                        shared: true,
                         retainedFileCountLimit: null
                     )
                    .CreateLogger();
            }
            catch (Exception ex)
            {
                LogFile.ConsoleDebug(Function, "Error Configuring Serilog", ex);
            }
        }
```

**Shell File:**
```
        public static void ShellFile(string stringFile)
        {
            string Function = System.Reflection.MethodBase.GetCurrentMethod().Name;
            try
            {
                //opens it with default handler/explorer
                System.Diagnostics.Process.Start(stringFile);
            }
            catch (Exception e1)
            {
                string serr = $"Unable to start Default Application for file '{stringFile}'";
                LogFile.LogError(Function, serr, e1);
            }
        }
```

**Problem:**
Calling System.Diagnostics.Process.Start() on the current Serilog.Sinks.File log file when the file sink is configured with 'shared: true' and the TargetFramework is 'netcoreapp3.1' generates an exception: 'System.ComponentModel.Win32Exception (32): The process cannot access the file because it is being used by another process.'. However when the TargetFramework is 'net48' the System.Diagnostics.Process.Start() call completes successfully.

**Expectation:**
In a .Net Core 3.1 WPF C# application calling System.Diagnostics.Process.Start() on the current Serilog.Sinks.File log file when the file sink is configured with 'shared: true' allows the file to be opened without error.

**Details:**
In a .Net Core 3.1 WPF project, both while running in the VS2019 IDE (Microsoft Visual Studio Professional 2019
Version 16.7.2) and when running the compiled WinEXE, calling System.Diagnostics.Process.Start(stringFile) on the current Serilog log file created with 'shared: true' fails with a "file is locked" error:

```
2020-09-25 07:08:12.405 -07:00 [ERR] ********************************************************************************
2020-09-25 07:08:12.405 -07:00 [ERR] Exception in Function : ShellFile
2020-09-25 07:08:12.405 -07:00 [ERR] Details ..........: Unable to start Default Application for file 'C:\Users\b\L.20200925_070807.txt'
2020-09-25 07:08:12.405 -07:00 [ERR] HResult ..........: 80004005; -2147467259
2020-09-25 07:08:12.405 -07:00 [ERR] Exception ........: System.ComponentModel.Win32Exception (32): The process cannot access the file because it is being used by another process.
2020-09-25 07:08:12.405 -07:00 [ERR]  .................:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
2020-09-25 07:08:12.405 -07:00 [ERR]  .................:    at System.Diagnostics.Process.Start()
2020-09-25 07:08:12.405 -07:00 [ERR]  .................:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
2020-09-25 07:08:12.405 -07:00 [ERR]  .................:    at System.Diagnostics.Process.Start(String fileName)
2020-09-25 07:08:12.405 -07:00 [ERR]  .................:    at LP.Utilities.ShellFile(String stringFile) in C:\Projects\test\source\L\L\Utilities.cs:line 468
```
The log file exists and is not being written to when attempting to shell it.  I can open the file manually using any number of text editors without error.

I have been using this code in .Net framework WPF applications for some time and was surprised that using the code in a project targeting the .Net Core 3.1 framework caused the log file to be marked as in use.  As a test I edited the TargetFramework (as shown above) in the .csproj to be .Net Framework 4.8 and the code worked, there was no error when calling ShellFile on the Serilog.Sinks.File log file.

**Comment by nblumhardt** [comment]
`shared` is only intended to support sharing with other Serilog file sinks, so I don't know if this will work for you on .NET Core (which uses a different shared file sink implementation), sorry.

**Comment by onicon-bschaefer** [comment]
Thank you for the explanation, I'll close this issue.

**Comment by onicon-bschaefer** [comment]
Closing, shared is only intended to work with other sinks not the application itself.
