### ISSUE TITLE
support 'logrotate' file naming/target strategy

### ISSUE THREAD

**Issue by neilwashere** [serilog/serilog-sinks-file#179]
The `logrotate` facility on many unix systems will move the target log file with an incrementing integer suffix:

eg `my.log' -> 'my.log.1'

The application will continue writing to 'my.log' which has now been recreated (It expects the supplying application to recreate the target file or logrotate can be instructed to create).

Having a single target file makes configuring consuming applications less troublesome. At the moment I am trying to
use fluentbit with a file consumer but require that the target file is rotated. I can't do this with the file rotation offered
by this sink. Unfortunately using the actual logrotate utility against files being written to by this sink is suboptimal - it
requires that the target file be truncated in-situ as moving/creating is not a possibility due to how the file is being
handled. This can lead to data loss (and ends up misreporting the target file size negating the usefulness of logrotation to
address disk usage).

I wonder if there is any appetite to change the file rotation strategy of this sink to make it more unix (logrotate) friendly.

**Comment by bartelink** [comment]
There's an issue covering the bulk of this desire in https://github.com/serilog/serilog-sinks-file/issues/40

**Comment by nblumhardt** [comment]
https://github.com/dfacto-lab/serilog-sinks-file is the work-in-progress, for anyone interested in helping this along or trying it out :+1:
