### ISSUE TITLE
Add Weekly as an interval type

### ISSUE THREAD

**Issue by camerontbelt** [serilog/serilog-sinks-file#181]
I would like to have the option of using Weekly as an interval type.

**Comment by cocowalla** [comment]
The other intervals have a natural, "obvious", suffix (e.g. for monthly it's `yyyyMM`, daily is `yyyyMMdd`) - what would you expect for files that roll on a weekly basis?

**Comment by camerontbelt** [comment]
@cocowalla I suppose you can check my PR, that should answer your question.
