### ISSUE TITLE
Custom Path for Serilog.Sinks.File

### ISSUE THREAD

**Issue by jean-paul-scorito** [serilog/serilog-sinks-file#185]
Hi!

I am looking for a way to integrate the variables (as they are used in an outputtemplate) into the path.
For example, I have multiple applications using the same base, they all use serilogging with serilog.json
I want them all to write to the same folder but add another layer of their application name.
So for example:
C:/Logs/{ApplicationName}/20201102.log

How can this be achieved?

**Comment by cocowalla** [comment]
You can use environment variables, e.g. each logger would have a path like:

```
%PROGRAMDATA%\\App1\\Logs
%PROGRAMDATA%\\App2\\Logs
```

**Comment by jean-paul-scorito** [comment]
Hi,

Thank you for your swift answer, I did see in the documentation that I can use Enviroment Variables, but I would like to use program variables as well.
Some things are saved in the Assembly for example and I would like to include those.
Is there any way to do this properly?

**Comment by cocowalla** [comment]
I should have also said, but if you are configuring your loggers programmatically (rather than with JSON/XML config files), then you can use whatever you like in log paths.

**Comment by jean-paul-scorito** [comment]
We are using json for .net core and xml for .net framework but we would like to use params inside the path like we used to with log4net, you could declare %property{ApplicationName}% and inside the application we would than set that property on startup
________________________________

**Comment by nblumhardt** [comment]
@jean-paul-scorito you can do the same thing with an environment variable, just call `Environment.SetEnvironmentVariable()` on start-up before configuring Serilog :+1:
