### ISSUE TITLE
What happened to retainedFileTimeLimit option

### ISSUE THREAD

**Issue by gokayokutucu** [serilog/serilog-sinks-file#188]
Is retainedFileTimeLimit option removed or renamed? I need to delete files older than specified days. Is there any way to do it?

**Comment by nblumhardt** [comment]
It's still there. You'll need to post what you've tried, and what error message you receive. HTH!

**Comment by gokayokutucu** [comment]
I installed `Serilog.Sinks.File 4.1.0`, but this parameter does not appear when using configuration with code. 
Here is the code that I used:
```
 new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .WriteTo.File(
                    path: "log-.log",
                    shared: true,
                    retainedFileCountLimit:100,
                    rollOnFileSizeLimit: fileSizeLimitBytes != 0,
                    fileSizeLimitBytes: fileSizeLimitBytes,
                    outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
                    rollingInterval: RollingInterval.Day)
                .Enrich.FromLogContext()
                .CreateLogger();
```

**Comment by nblumhardt** [comment]
Sorry, my mistake - you need the 5.0.0-dev* versions of the package for this.

**Comment by gokayokutucu** [comment]
OK, thanks!

**Comment by hnigam-git** [comment]
@nblumhardt We have been waiting for this feature for long. When do you plan to merge this change to master?

**Comment by nblumhardt** [comment]
Thanks for the nudge! How is the `-dev` package going for you? Does the feature work the way you need it to, @hnigam-git ?

Release PR is now open https://github.com/serilog/serilog-sinks-file/pull/210
