### ISSUE TITLE
IO Exception - fails to release file lock?

### ISSUE THREAD

**Issue by TomPeters** [serilog/serilog-sinks-file#19]
The following code works fine:

    class Program
    {
        static void Main(string[] args)
        {
            using (var logger = CreateLogger())
            {
                logger.Information("foo");
            }
            using (var logger = CreateLogger())
            {
                logger.Information("bar");
            }
        }

        private static Logger CreateLogger()
        {
            return new LoggerConfiguration()
                .WriteTo.File("C:/temp/mytestlogfile.log")
                .CreateLogger();
        }
    }

But if I add a minimum level to the file sink, it now throws an exception:

    class Program
    {
        static void Main(string[] args)
        {
            using (var logger = CreateLogger())
            {
                logger.Information("foo");
            }
            using (var logger = CreateLogger()) // throws here
            {
                logger.Information("bar");
            }
        }

        private static Logger CreateLogger()
        {
            return new LoggerConfiguration()
                .WriteTo.File("C:/temp/mytestlogfile.log", LogEventLevel.Information) // throws here
                .CreateLogger();
        }
    }

Exception: 
`System.IO.IOException occurred
  HResult=-2147024864
  Message=The process cannot access the file 'C:\temp\mytestlogfile.log' because it is being used by another process.
  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
  InnerException: 
`

I presume in the latter case, the file sink is not being disposed along with the logger.
The workaround is to add the minimum log level to the LoggerConfiguration instead of the file sink.

**Comment by nblumhardt** [comment]
Thanks for the report, Tom. Remarkably, this was just fixed in `dev` about 5 minutes ago: https://github.com/serilog/serilog/issues/870.

The dev package is published as: https://www.nuget.org/packages/Serilog/2.3.0-dev-00719

Would you be able to confirm that updating your Serilog dependency to 2.3.0-dev-00719 fixes this for you?

Best regards,
Nick

**Comment by TomPeters** [comment]
That did the trick, thanks Nick

**Comment by nblumhardt** [comment]
Thanks!
