### ISSUE TITLE
Add ability to get the file path of the log file via hooks

### ISSUE THREAD

**Issue by augustoproiete** [serilog/serilog-sinks-file#191]
Over time I've seen a few questions on StackOverflow asking for a feature similar to what's being asked on https://github.com/serilog/serilog/issues/1489 which is the ability to inspect the properties of the sinks configured, at run-time.

That feature is a bigger piece of work that requires design, of course, however in many of those questions, devs were aiming to use such a feature just to get a hold of the path of the file being written by this sink in particular, for different reasons (\*).

I propose adding the log file path to the existing `OnFileOpened` hook, which would allow devs to plug in a hook that captures the file path of every log file written and keep track of the most recent one.

This would provide a workaround for this particular scenario until https://github.com/serilog/serilog/issues/1489 or something similar becomes available.

Also, for consistency, the `OnFileDeleting` hook already exposes the file path, and I couldn't think of a reason why `OnFileOpened` wouldn't do the same.

---

(\*) I can remember of a couple of examples where devs would like to know the exact file name (considering the name changes with rolling) in order to do run some activity:

- [Get the path to the log file without having to read the app's configuration file, expand environment variables, etc](https://stackoverflow.com/questions/61143684/how-to-get-the-serilog-log-path-from-application-configuration-file)
- [Show a message to the end-user on a desktop app showing where the log file (or folder) is](https://stackoverflow.com/questions/64579477/get-current-serilog-configuration-to-know-full-write-to-file-path)
- [Email the most recent log file to someone before an app closes](https://stackoverflow.com/questions/61317806/email-the-log-file-created-at-the-end-of-program-using-serilog)

**Comment by cocowalla** [comment]
I expected there to be some discussion and evolution once hooks hit the stable version and they became more visible, nice to see it happening 😄 

The `OnFileDeleting` hook has the path of the file being deleted, and the scenarios given make sense - I don't know what you think @nblumhardt, but I'm in favour of this change 👍

Only thing I'd add is, to try to avoid churn: aside from filename, is there any other information that might be required? (I can't personally think of any)
