### ISSUE TITLE
Log file is not getting created when project published as a SingleFile

### ISSUE THREAD

**Issue by adurmus** [serilog/serilog-sinks-file#193]
When a console app (.net 5) published with the following command  and executable is run the log file is not getting generated. 

`dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true`

appsettings.json 

```
"Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "C:\\Logs\\Log.txt",
          "rollingInterval": "Day"
        }
      }
    ]
  }
```

**Comment by skomis-mm** [comment]
Hi @adurmus ,
Try add `Using` section
```json
"Using": [ "Serilog.Sinks.File" ]
```
with the latest preview version of `Serilog.Settings.Configuration` package.
See [this](https://github.com/serilog/serilog-settings-configuration/issues/239) issue

**Comment by adurmus** [comment]
That worked. Thanks
