### ISSUE TITLE
Trying to get Console.WriteLine handled by Serilog File Sink

### ISSUE THREAD

**Issue by simonsabin** [serilog/serilog-sinks-file#197]
I've a console app that it using library that is outputing to the console with Console.Write. I would like that output to go to the same file as the Serilog config. But I can't seem to intercept them to go to the.

One could just direct the app execution but then you don't get the output in the console. 

I tried to override the console.out stream but one can't detect what is coming from serilog i.e. log.Logger.... and whats come from direct calls to Console.Write...

Is this solveable?

**Comment by nblumhardt** [comment]
Thanks for the note, @simonsabin - it's outside of the scope of what this sink can provide; it sounds like you'll need to override the console output stream with a custom stream of your own, forward the output to the original stream, buffer and watch for newlines, send the buffered lines to the file sink.... it's a challenging project to take on :-)

**Comment by simonsabin** [comment]
Yep, not a simple config. Thats the assumption I'd come to.
