### ISSUE TITLE
Strange behavior with rolled file when locked

### ISSUE THREAD

**Issue by brian-pickens** [serilog/serilog-sinks-file#201]
I'm trying to determine what sequence of events could cause the following behavior. A deployment in our test environment triggered an overlapped recycle of the web application. I can see in the selflog where the file was locked and so the sequence was incremented. Thats not the odd part. The odd part is that logging in that 002 sequence file continued for only about 30 seconds. After that 30 second period, the logging to the 002 file stopped and continued again in the 001 sequence file. This is odd to me because I understand from reading the code in the RollingFileSink that any new instance should log to the most recent file in the sequence.

![image](https://user-images.githubusercontent.com/3659859/107824487-2a9d7580-6d47-11eb-9775-c1942343e390.png)

**Comment by nblumhardt** [comment]
Thanks for the note! No idea what sequence of events would lead to this either, but, chances are it was a race between different processes, which aren't coordinated at all by the sink. In the end, when there's a race over a directory full of files, the sink does its best but doesn't make any hard guarantees about this kind of thing.

**Comment by brian-pickens-web** [comment]
Thanks for the quick response. Race condition was my only conclusion too. But for a race condition to exist in this context, wouldn't recycling have had to have been triggered more than once with possibly two instances being loaded into memory by IIS? Very odd. You can close this issue. I just wondered if you or anyone on this project might have some insight.

**Comment by tkrafael** [comment]
@brian-pickens-web tipically IIS will start a new instance while telling the former to be stopped.
You can verify if overlapping is occuring by looking at advanced settings in application pool.
