### ISSUE TITLE
Allow dynamic File retention count

### ISSUE THREAD

**Issue by sensslen** [serilog/serilog-sinks-file#203]
This sink currently allows to specify a number of files to be retained. In our application we would like to adjust this number on the fly and have the appropriate files deleted when the value is adjusted immediately.

**Comment by cocowalla** [comment]
Appreciate you opening the issue! 

On the face of it, this seems like a very niche requirement - are you able to say a bit more about why you need to do this?

**Comment by nblumhardt** [comment]
A wrapper sink (or tricky use of `Serilog.Sinks.Map`) should be able to implement this as an unintrusive workaround. E.g.:

```csharp
volatile int _retainedFileCountLimit;

// Elsewhere
    .WriteTo.Map(
        _ => _retainedFileCountLimit,
        (wt, limit) => wt.File(..., retainedFileCountLimit: limit),
        sinkMapCountLimit: 1)
```

As @cocowalla suggests, it's probably too unusual a requirement for us to add first-class API support, here.

**Comment by sensslen** [comment]
@cocowalla 
Ok, let me explain the reasoning for this feature:
we are using serilog on an embedded device (in this case a raspberry pi). While there is some storage space available, it is certainly much less than on a traditional computer. This feature gives us the ability to react to situations in which we want to remove files that have lower priority in favour of high priority files (e.g. Software updates).

@nblumhardt 
Regarding the map feature I do not think this will work:
If I understand correctly, the file sink applies the file retention policy when a new file is about to be created. Unfortunately this leads to the weired situation that we want to (lets say keep only 20 of our 30 log files) but the obsolete files are only being deleted upon creation of the next file. 

Therefore the only other viable solution I can think of is to monitor the files in the application (which I find very hacky).

Please correct me if I am wrong with my analysis.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, @sensslen!

It's an interesting scenario - but still one that seems better left for either a fork or custom sink implementation.

Once we integrate this kind of functionality, here, we need to maintain and test it pretty much indefinitely, including considering it whenever we make other additions or improvements.

We've so far managed to keep this codebase approachable by being very selective about what scenarios the package targets (ironically, this is why many small additions like this one still seem fairly easy to make :-) )

Hope this helps explain our reasoning, and if you end up building a fork or new sink for low-resource environments, it would be extremely interesting to hear how it goes/what you come up with!

Cheers,
Nick

**Comment by sensslen** [comment]
While I would have really liked to get this addition into the project, I accept your decision. We will therefore spin our own file sink internally. ---> Closing this.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. If you need any help getting your custom sink to work as you would like, please don't hesitate to drop us a line :+1:
