### ISSUE TITLE
Lazy logfile creation for RollingInterval.Infinite

### ISSUE THREAD

**Issue by chtenb** [serilog/serilog-sinks-file#212]
When a non-infinite rolling interval is specified, de file sink is created as soon as the first log event is emitted.
However, when the rolling interval is infinite, the logfile is created as soon as the logger is initialized.

I would like to have the lazy behavior for the infinite rolling interval as well.
I'm using different file sinks for different minimum error levels, which allows me to see at a glance if there were any errors just by looking at the files that are created.
(Apart from that, all the empty logfiles throw a spanner in the works of other machinery that processes the log files. It would be nice not having to deal with empty logfiles.)

**Comment by nblumhardt** [comment]
Thanks for the note. It's unlikely we'll make this change in the sink at this point. Forking/customizing should be straightforward however (feel free to jump back in if you need any help with it).
