### ISSUE TITLE
Precise rolling interval

### ISSUE THREAD

**Issue by Parsa2820** [serilog/serilog-sinks-file#213]
We need to specify rolling interval more accurate than just `Minute`, `Hour`, `Day`, `Month`, `Year`, and `Infinite`. How about adding a new parameter besides current `RollingInterval`  enum parameter, for example `string preciseRollingInterval` which can get values like `"2h 30m 4s"`?

This is the orginal comment on a PR : https://github.com/serilog/serilog-sinks-file/pull/182#issuecomment-809934787

**Comment by tkrafael** [comment]
https://github.com/serilog/serilog-sinks-file/pull/204

**Comment by bartelink** [comment]
Realistically the current high level approach of defining rolling intervals is [not something that's viable to change given the broad use of this sink](https://github.com/serilog/serilog-sinks-file/issues/243#issuecomment-1404297429)

Closing as a duplicate of #243, #225 and/or #298 - [the most viable way for anything to change is to have a fork demonstrate something that works, take the learnings from that, map it to a feature request here, and have someone implement it](https://github.com/serilog/serilog-sinks-file/issues/298#issuecomment-1762663305)
