### ISSUE TITLE
Log both Message and Message Template

### ISSUE THREAD

**Issue by jlcarpenter** [serilog/serilog-sinks-file#214]
I'm writing logs to a file and have tried JsonFormatter, CompactJsonFormatter, and RenderedCompactJsonFormatter.  It seems these either log the message template or not the message.  Is there a way to log both?  Below is info from my appsettings file.

"WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "c:\\\\logs\\log.json",
          "rollingInterval": "Day",
          //"formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "renderMessage": true
          //"outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] [{ThreadId}] [{SourceContext}]: {MessageTemplate}{Message}{NewLine}{Exception}"
        }

**Comment by nblumhardt** [comment]
Hi! It's not (yet) directly compatible with JSON config, but [_Serilog.Expressions_](https://github.com/serilog/serilog-exceptions) can do what you want:

```csharp
    // dotnet add package Serilog.Expressions
    // using Serilog.Templates;
    .WriteTo.File(
        new ExpressionTemplate(
                "{ {..@p, @t, @m, @mt, @r, @l: if @l = 'Information' then undefined() else @l, @x} }" + Environment.NewLine),
        "c:\\logs\\log.json",
        rollingInterval: RollingInterval.Day)
```
