### ISSUE TITLE
Can't see all of my trace event details

### ISSUE THREAD

**Issue by gorkemhacioglu** [serilog/serilog-sinks-file#216]
Hello,

I use `System.Diagnostics.TraceSource.TraceEvent` method to write log, and I am listening it with this output template ;
{Timestamp:yyyy-MM-ddTHH:mm:ss.fffffff} | {Level:u4} | {Message:lj}{NewLine}{Exception}

But I can not see all of my log details at {Message}. Is there any another formats to see all of the TraceEvent details?

**Comment by tkrafael** [comment]
Can you provide what you would like to see in trace event?

**Comment by gorkemhacioglu** [comment]
For example;

System.Diagnostics.TraceSource Source;

var format = "This is a sample log at {0}";

Source.TraceEvent((TraceEventType)eventTypes, id, format, args); //args contains a string value.

I want to see the combination of format + args.
