### ISSUE TITLE
SharedFileSink: logger.Log thrown System.IO.IOException and stop to write LogEvents

### ISSUE THREAD

**Issue by sasha-khadasevich** [serilog/serilog-sinks-file#218]
Hi,
`logger.Log` thrown System.IO.IOException: 'Unable seek backward to overwrite data that previously existed in a file opened in Append mode.' when another application tries to truncate log file.
Logger configuration (version 4.0.0):
`loggerConfiguration.WriteTo.File("Log.log", shared: true);`

Another app try to clean log file with following code:
`new FileStream("Log.log", FileMode.Truncate, FileAccess.Write, FileShare.ReadWrite);`

In case, when write to file and file truncate occurs simultaneously, the next `logger.Log` thrown System.IO.IOException: 'Unable seek backward to overwrite data that previously existed in a file opened in Append mode.' StackTrace    "   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)"    string

I know, that serilog-sinks-file didn't explicitly design for this scenario. [https://github.com/serilog/serilog-sinks-file/issues/73](url)
But is it possible to add to SharedFileSink code, that opens the file one more time with append mode in case of such failures?
`_underlyingStream = System.IO.File.Open(path, FileMode.Append, FileAccess.Write, FileShare.ReadWrite);`

**Comment by nblumhardt** [comment]
Hi; currently this is an edge case we're unlikely to support in the sink; customizing/forking the sink may be a good solution, however. HTH!
