### ISSUE TITLE
Provide an extension .part to the file getting written to.

### ISSUE THREAD

**Issue by pankaj-k** [serilog/serilog-sinks-file#219]
Hi,

Right now the file sink creates file like this based on size.
Logs20210519.json
Logs20210519_001.json
Logs20210519_002.json
Logs20210519_003.json

with Logs20210519_003.json being the latest one. 

Is it possible to provide an option to the interested users to enable them to configure the sink to write the files like this:
**Logs20210519.json.part**
Logs20210519_001.json
Logs20210519_002.json
Logs20210519_003.json

This will allow us to configure our monitoring processes to consume the files excluding the one ending in .part and move/delete them after processing their data.

**Comment by cocowalla** [comment]
Does your monitoring software support regex, wilcards, globs, or something else?

**Comment by pankaj-k** [comment]
I am using filebeats and it does support these. I am however not able to put my head around how to write a regex which will match Logs20210519.json, Logs20210519_001.json, Logs20210519_002.json but **not** Logs20210519_003.json.

**Comment by cocowalla** [comment]
Ah sorry, I'd misread your first post, that's what I get for heading to GitHub Notifications before coffee 😅.

I think then, this is essentially a duplicate of #40 (use a fixed filename for the current, active log).

**Comment by pankaj-k** [comment]
Yeah it is. I will close this.
