### ISSUE TITLE
Cannot log exceptions in UseSerilog when using bootstrap logger

### ISSUE THREAD

**Issue by ieyj** [serilog/serilog-sinks-file#220]
Steps to reproduce:
1. use dotnet core 3.1 or 5.0, new a webapi project using `dotnet new webapi`
2. add serilog reference by `dotnet add package Serilog.AspNetCore`
3. Modify the Program.cs as follows:(using is omitted)
```csharp
namespace SerilogTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            SelfLog.Enable(Console.Out);

            Log.Logger = new LoggerConfiguration()
            .WriteTo.Console()
            .WriteTo.File("log.txt")
            .CreateBootstrapLogger();

            try 
            {
                CreateHostBuilder(args).Build().Run();
            }
            catch(Exception ex)
            {
                Log.Fatal(ex, "fatal");
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .UseSerilog((context, services, configuration)=>{
                throw new Exception();
            })
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
    }
}
```

Note that I throw an exception in the UseSerilog method, and I wish serilog log this exception in the Main mehtod catch block.
The console sink does log the exception but the file sink log nothing.

I use `SelfLog.Enable(Console.Out);` and an expection was logged:

```log
Caught exception while emitting to sink Serilog.Sinks.File.FileSink: System.ObjectDisposedException: Cannot write to a closed TextWriter.
Object name: 'StreamWriter'.
   at System.IO.StreamWriter.<ThrowIfDisposed>g__ThrowObjectDisposedException|75_0()
   at System.IO.StreamWriter.Write(String value)
   at Serilog.Events.ScalarValue.Render(Object value, TextWriter output, String format, IFormatProvider formatProvider)
   at Serilog.Formatting.Display.MessageTemplateTextFormatter.Format(LogEvent logEvent, TextWriter output)
   at Serilog.Sinks.File.FileSink.Serilog.Sinks.File.IFileSink.EmitOrOverflow(LogEvent logEvent)
   at Serilog.Sinks.File.FileSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

When I changed `CreateBootstrapLogger()` to `CreateLogger()`, everything works fine, so think the problem is related to the bootstrap logger.

**Comment by nblumhardt** [comment]
You're missing `Log.CloseAndFlush()` as the last line of your `Main()` method. Does this help?

**Comment by ieyj** [comment]
> You're missing `Log.CloseAndFlush()` as the last line of your `Main()` method. Does this help?

Not because of this. I have `Log.CloseAndFlush()` in my production code.  The key to this problem is Serilog.Sinks.File throw an exception of using disposed resources. I don't know it's a problem of `CreateBootstrapLogger()` or `Serilog.Sinks.File`. Maybe it's a problem of `Serilog.Extensions.Hosting`.

For whom misses this problem, this code will help:

```csharp
catch(Exception ex)
{
    if(Log.Logger == null || Log.Logger.GetType().Name == "SilentLogger"
                                       || Log.Logger.GetType().Name == "ReloadableLoggert")
    {
        Log.Logger = new LoggerConfiguration()
            .WriteTo.File("log.txt")
            .CreateLogger();
    }

    Log.Fatal(ex, "fatal");
}
```

In fact, you don't really need to use Bootstrap Logger if using this pattern.

**Comment by ieyj** [comment]
Exceptions in `UseSerilog()` method such as a wrong logging configuration may casue the programe failed to start directly and it need to be logged.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Unfortunately, I think this is an unavoidable issue when using `CreateBootstrapLogger`: the current logger will always need to be closed/disposed before the new one can be created, since the file sink (and others) must release exclusive locks so that new sinks can acquire them.

Exceptions thrown while configuring logging are tricky to catch; it'd be interesting to think about how we might improve the experience, but for now I think this is by design and we won't be able to work around it in the near future.
