### ISSUE TITLE
File Location When Running as a Windows Service is in System32 Directory

### ISSUE THREAD

**Issue by DavidRogersDev** [serilog/serilog-sinks-file#223]
When running an application as a Windows Service (e.g. the new _Worker Service_ template in VS), the current directory is %WINDIR%\system32 , rather than whatever directory the exe is actually running in.

That is, `Directory.GetCurrentDirectory()` returns %WINDIR%\system32

This is fixable in C#, by using a different API call to get the executing directory. E.g. 
`Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)`

However, if using a JSON file to configure Serilog, there is no way to change the relative path, in such a way.
Of course, an absolute path still works (but when has that ever been a good idea? 😉 ) .

Perhaps a change to the code in this sink which is resolving the current directory could be changed using reflection (as set out in the code snippet above).

Not sure if that would impact perf, but some kind of "lazy get" should address that.

Thanks

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. One thing you might try in the JSON config scenario is to use environment variables like `%APPDATA%` in your log file path. _Serilog.Settings.Configuration_ will replace these correctly, and often, those are better locations for log files on Windows than wherever the EXE is being run from. HTH!

**Comment by DavidRogersDev** [comment]
Cool. Thanks for that. I did see that somewhere, except it was in the context of Environment Variables. I think %APPDATA% might be a good solution, as I would not need to create an environment variable on a client's server.
Been using Serilog for years now.
Thanks again.

**Comment by nblumhardt** [comment]
:+1:

**Comment by wuzhenda** [comment]
I run the app as a windows service, and will save a log of  big log files. the %APPDATA% or %TEMP% all at C disk. if I want to save log files at the current running  app directory, which is a relative file path ,how can I?

**Comment by augustoproiete** [comment]
@wuzhenda See https://stackoverflow.com/a/68746437/211672

**Comment by wuzhenda** [comment]
tks for reply.
it's strange for serilog, as we did well with log4net.

**Comment by bthulu** [comment]
is there any method to specify path in .json file like below?
```
      {
        "Name": "File",
        "Args": {
          "path": "%xxx%/logs/log-.txt",
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} {Level:u3} {SourceContext}: {Message:lj}{NewLine}{Exception}",
          "retainedFileCountLimit": 20,
          "rollingInterval": "Day",
          "fileSizeLimitBytes": 10485760,
          "rollOnFileSizeLimit": true
        }
      }
```

**Comment by bartelink** [comment]
@bthulu Best to ask things like this on stackoverflow rather than necroposting where only very few people will ever see them (I'd look in the Serilog Configuration module's readme, implementation and/or issues for the answer if I wanted to know)

**Comment by cocowalla** [comment]
> is there any method to specify path in .json file like below?

Yes, you can use environment variables in the path. I typically do this to write to `%PROGRAMDATA%`, which is a standard'ish place to put logs on Windows, e.g.

```json
"WriteTo": [
  {
    "Name": "File",
    "Args": {
      "rollingInterval": "Day",
      "retainedFileCountLimit": 90,
      "path": "%PROGRAMDATA%\\My App\\log\\my-app-.log",
      "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {Level} {EventId:x8} {ThreadId} [{SourceContext:l}] {Message:l}{NewLine}{Exception}"
    }
  }
]
```

**Comment by bthulu** [comment]
finally i set env variable at the first line of Program.cs
```
Environment.SetEnvironmentVariable("APP_BASE_DIRECTORY", AppContext.BaseDirectory);
```
then use %APP_BASE_DIRECTORY%/logs/log-.txt in path
```
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "%APP_BASE_DIRECTORY%/logs/log-.txt",
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} {Level:u3} {SourceContext}: {Message:lj}{NewLine}{Exception}",
          "retainedFileCountLimit": 20,
          "rollingInterval": "Day",
          "fileSizeLimitBytes": 10485760,
          "rollOnFileSizeLimit": true
        }
      }
    ],
```

**Comment by sunzhengbo** [comment]
### appsettings
`{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "File",
        "Args": {
          "path": "%APP_BASE_DIRECTORY%/Logs/log-.txt",
          "rollingInterval": "Day"
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
  }
}
`
### Program.cs
`using Microsoft.Extensions.Hosting.WindowsServices;
using Serilog;
using WindowsService;



var builder = Host.CreateDefaultBuilder(args);
if (WindowsServiceHelpers.IsWindowsService())
{
    builder.UseWindowsService();
    Environment.SetEnvironmentVariable("APP_BASE_DIRECTORY", AppContext.BaseDirectory);
}
else
{
    Environment.SetEnvironmentVariable("APP_BASE_DIRECTORY", Directory.GetCurrentDirectory());
}
IHost host = builder
    .UseSerilog((context, services, configuration) =>
    {
        configuration
        .ReadFrom.Configuration(context.Configuration)
        .ReadFrom.Services(services);
    })
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .Build();

await host.RunAsync();
`

**Comment by Misiu** [comment]
or you can set the application's current directory (at application start):
```
Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);
```

this works on Windows 10 when the application is run from the scheduler. I didn't test windows service, but it should work similarly.

**Comment by scottmwyant** [comment]
@nblumhardt -- It may be time to revisit this.  I believe Serilog should mirror how we've seen the hosting model evolve... I may need to do some homework on this but it seems that `IHostEnvironment.ContentRootPath` returns current working directory unless the app is being run as a service, then it will move to `AppContext.BaseDirectory`.

- [IHostEnvironment.ContentRootPath](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment.contentrootpath?view=net-10.0-pp#microsoft-extensions-hosting-ihostenvironment-contentrootpath)
- [AppContext.BaseDirectory](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=net-10.0)

The options listed in this thread both valid, first set the working directory, or, use a well-known path like `%APPDATA%`.  Do you agree with my suggested behavior? Should I submit a new issue?

**Comment by nblumhardt** [comment]
@scottmwyant thanks for taking a look.

I don't think the gains would be worth the breakage; for example, anyone expecting to find logs in `system32`, or setting the working directory at program start, would be broken if we change the default. These would normally be edge cases, but the breadth of deployment of this package is pretty huge, so a nontrival number of apps would be silently disrupted.

Going back in time I'd possibly approach this differently and force the supplied path to be fully-qualified, either as a rooted path, or with a `%BASEDIR%`, `%CWD%` or environment-variable prefix. Or something along those lines. Still some footguns even then, no doubt :-) ... Guess I live and learn 😅

**Comment by bartelink** [comment]
I agree a breaking change is out of the question.

Perhaps there's something that could be added to the xmldoc?

Or a BaseDir property and/or ctor arg that gets used if the `path` is not rooted?

**Comment by nblumhardt** [comment]
Did give those things a thought, too ... Discoverability is a challenge, additional args and XDOC can also easily be missed, and it's easy to just accumulate bloat. I'm not against it, but have doubts we'll really move the needle.

The `path` XDOC is pretty minimal, though:

```csharp
    /// <param name="path">Path to the file.</param>
```

Perhaps we could bump that up to:

```csharp
    /// <param name="path">Path to the file. Absolute paths are recommended. Relative paths will be resolved
    /// under the current working directory at runtime (i.e. <c>%WINDIR%\System32</c> for Windows services).</param>
```

?

**Comment by scottmwyant** [comment]
Totally agree, need to preserve existing behavior. Perhaps this isn't the right repo and this concept should be handled under Serilog.Settings.Configuration?  I'm wondering if an opt-in like `.UseContentRootBasePath()` would be appropriate.
