### ISSUE TITLE
How to configure log path like configuring pathformat of serilog-sinks-rollingfile?

### ISSUE THREAD

**Issue by fishdrinkmilk** [serilog/serilog-sinks-file#231]
How can I config the path like this ?How to make it gerenate log path by date?

"Serilog": {
    "Using": ["Serilog.Sinks.File"],
    "MinimumLevel": "Debug",
    "WriteTo": [
        {
            "Name": "File",
            "Args": {
                "path": "{yyyy}\{MM}\{dd}.log"
            }
        }
    ]
}

**Comment by nblumhardt** [comment]
Hi! This sink only supports a few simple rolling strategies and does not bring across the old path formatting technique. At this point it's unlikely the sink will be extended in this way.
