### ISSUE TITLE
In the sub logger ,the rollingInterval: RollingInterval.Day do not work!

### ISSUE THREAD

**Issue by yuxin5156** [serilog/serilog-sinks-file#234]
when i use the under code,the log file not generate,when i remove the param [rollingInterval: RollingInterval.Day],it works ,but can not RollingDays ，what should I do?
当我使用以下代码时，日志文件没有生成，当我去掉参数rollingInterval后，日志生成了，但是不能按天滚动了，什么情况？
```
       Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)//屏蔽请求日志
            .WriteTo.Logger(opt => opt
                .Filter.ByIncludingOnly(Matching.FromSource<DemoController>())
                .WriteTo.File(path: "logs/smart-water-.txt", rollingInterval: RollingInterval.Day))
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .WriteTo.File(path: "logs/szrh-.txt", rollingInterval: RollingInterval.Day)
            .CreateLogger();
```

**Comment by nblumhardt** [comment]
Howdy! Do you see anything in `SelfLog` when you run the app with the last line present? https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics#selflog

**Comment by nblumhardt** [comment]
Closing as stale; if you spot something in SelfLog please feel free to jump in and let us know here. Thanks!
