### ISSUE TITLE
Support RollingInterval Execution

### ISSUE THREAD

**Issue by puschie286** [serilog/serilog-sinks-file#236]
Hi, we are using one log per appliaction execution for development - by simple add DateTime.Now:yyyy.MM.dd.HH.mm.ss to the filename. this works find but some other options like retainedFileCountLimit seems to not work when the log file name is changed by the application and not by serilog.

would be nice if it would be supported nativly.

our current workaround is to clear all logs as pre build event (IDE)

**Comment by trungdang194** [comment]
I got the same issue with filename format is customize with additional of Guid added, retainedFileCountLimit cannot detect any files to do delete file function.
Is there any enhancement to support configuring _filenamePrefix, DirectorySearchPattern in PathRoller.cs?

**Comment by nblumhardt** [comment]
Hi, thanks for your message. This one is a bit of an edge case and unlikely to receive direct support in the sink. Creating your own custom sink would be your best bet here. HTH
