### ISSUE TITLE
Support for log file archiving

### ISSUE THREAD

**Issue by h0tspur** [serilog/serilog-sinks-file#237]
Hi, is there support for archiving log files at the end of the day? At the end of a day, the contents of the log file should be copied over to a file with the date stamp and the actual log file should be cleared for logging events of the next day.

Here is the expectation: at fixed intervals (for example at the end of the day), contents of log file (say `log.txt`) should be written to a `log_archive_ddmmyyy.txt` and `log.txt` should be cleared so that the events for the next interval can be captured.

This can be achieved by a service or a script, but it would be great if this was supported in the library.

**Comment by bartelink** [comment]
Perhaps https://github.com/dfacto-lab/serilog-sinks-file matches your needs? (this sink is intentionally minimal in the things it directly does, and in how many hard-to-manage-with-high-concurrency-cleanly it avoids doing - see some of the issues like #40 that delve into that discussion more deeply)

**Comment by cocowalla** [comment]
It's not exactly what you're asking for, but there is a plugin, [serilog-sinks-file-archive](https://github.com/cocowalla/serilog-sinks-file-archive), which can archive log data to another location (optionally compressed) before log files are deleted by Serilog's retention mechanism.
