### ISSUE TITLE
Log with server date time

### ISSUE THREAD

**Issue by mihaimyh** [serilog/serilog-sinks-file#238]
Is there a way to see the server date time in a file log? If I am not mistaken, by default, it logs to UTC.

**Comment by cocowalla** [comment]
Serilog uses server-local time by default. If wanted, you can include the time zone in the logs, using an output template such as (note the `zzz`):

```
{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}
```

If you want to use UTC instead, please see [here](https://github.com/serilog/serilog/issues/1419#issuecomment-623056843) or [here](https://github.com/serilog/serilog/issues/1024#issuecomment-338518695).
