### ISSUE TITLE
Allow to use with ILoggingBuilder.

### ISSUE THREAD

**Issue by AraHaan** [serilog/serilog-sinks-file#245]
Currently there seems to be no way to add the file logger to an ILoggingBuilder for configuring logs in a special way (when using Microsoft.Extensions.Logging as well to filter certain logs as well).

**Comment by augustoproiete** [comment]
@AraHaan Have you seen [Serilog.Extensions.Logging](https://github.com/serilog/serilog-extensions-logging) yet? If that is not what you're asking for, please provide examples of what you are trying to achieve.

**Comment by AraHaan** [comment]
I did, but I am not sure if it supports using non-rolling logs without any file size limits like what can be configured with ``Serilog.Sinks.File`` currently.

**Comment by augustoproiete** [comment]
It does - take it for a spin.
