### ISSUE TITLE
Explicit Flushing 

### ISSUE THREAD

**Issue by JLorch** [serilog/serilog-sinks-file#247]
We have a scenario where we want to use a buffered FileSink with a flush interval of lets say 5 seconds. If a critical error (above a certain log level) is logged we want to increase our chances of logging this to file (as the application might be unstable at this point and the periodic flush might not happen) and performing an explicit flush of the log. 

Is this possible to achieve?

**Comment by nblumhardt** [comment]
Thanks for the note; no, there's no explicit flushing feature implemented today. Are the errors you're interested in `Fatal`/`Critical`? I don't think we'd expose an API for this, but it could be interesting to investigate flushing automatically when an event at this level is observed.

**Comment by JLorch** [comment]
Yes, the error levels that would make sense for our use case is probably Error and Fatal. Information that could be very valuable for fault tracing.

**Comment by nblumhardt** [comment]
Thanks for your reply. I think `Error` could be problematic - generating a large number of errors is not uncommon, and adding flush overhead to these could make a bad situation worse. `Fatal` is different in that it is supposed to communicate a probable-termination or similar scenario, where a flush to disk should usually make sense.

Thinking some more, I wonder if there's a way to implement this today using a wrapper sink and `FileLifecycleHooks`?

The wrapper sink would wrap the file sink, and pass in its lifecycle hooks implementation, which would give it a chance to capture a reference to the underlying file stream. Then, after forwarding an event through to the wrapped sink, the wrapper could flush the file, if the level of the event was error/fatal? 🤔

**Comment by nblumhardt** [comment]
Closing as I think the workaround above is the best current option; if you're still keen to implement this, let us know, happy to help work through it.

**Comment by BernhardMarconato** [comment]
Using `FileLifecycleHooks` is no suitable workaround, as you can only access the `Stream` and flush it, but for example the `FileSink` also needs to flush the `TextWriter`. 

I would propose to add something alike:

```c#
public static LoggerConfiguration File(this LoggerSinkConfiguration sinkConfiguration, LogEventLevel forceFlushAtMinimumLevel, ...)
```

The default value would be `Fatal`, but users could disable it completely or even force to flush all the time.
@nblumhardt What are your thoughts? I am willing to create a PR for it. Thanks!
