### ISSUE TITLE
Serilog is not renewing the file name after day change .net core

### ISSUE THREAD

**Issue by jacgandres** [serilog/serilog-sinks-file#250]
I have seen that my windows services still logging into the same file day and day and is not renewing the file name

I have configured this

   private static void AddSerilog(IConfiguration configuration, ILoggingBuilder loggingBuilder)
        {
            var outputTemplate = configuration.GetSection("OutputTemplate").Get<string>();
            var rollOnFileSizeLimit = configuration.GetSection("RollOnFileSizeLimit").Get<bool>();
            var fileSizeLimitBytes = configuration.GetSection("LogMaxFileSize").Get<long>();
            var logFilePath = configuration.GetSection("PathFormat").Get<string>();

            var logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.File(
                    path: logFilePath,
                    outputTemplate: outputTemplate,
                    rollOnFileSizeLimit: rollOnFileSizeLimit,
                    fileSizeLimitBytes: fileSizeLimitBytes, 
                    rollingInterval: RollingInterval.Day,
                    shared: true)
                .CreateLogger();

            loggingBuilder.AddSerilog(logger);
        }

any idea?

**Comment by bartelink** [comment]
I would ask on SO: lots more eyes and quicker answers - the issues here are better for drilling into proven bugs; my assumption would be that [`SELECT` aint broken](https://blog.codinghorror.com/the-first-rule-of-programming-its-always-your-fault/) given how many people use this package...

My wild guess is that the roll-over is in UTC terms and you are looking from a different TZ perspective.

If I wanted to know the answer I'd go look in the tests (though asking on SO would probably be as quick)

**Comment by Shon1N** [comment]
You have probably done this but, can you confirm that you have the Serilog.Sinks.File package installed?
if you do this in the appsettings.json you can specify using Serilog.Sinks.File, not sure if that is what you are missing.

`"Using": [ "Serilog.Expressions", "Serilog.Sinks.File", "Serilog.Sinks.MSSqlServer" ]`

**Comment by bartelink** [comment]
@Shon1N Best we get this discussion moved out to SO.
@jacgandres For me, the `WriteTo.File` says you have referenced the package but are not trying to use `Serilog.Extensions.Logging`, but it would help to mention the specific packages and versiosn you are using in your SO question, along with the full wiring snippets

**Comment by nblumhardt** [comment]
May also be that the file dates are in UTC, so may not roll over at the same time as your local calendar day.
