### ISSUE TITLE
Log in CSV format

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog-sinks-file#252]
Apologies if this is the wrong repo!

Does anyone have guidance for logging to a csv file? Not just the extension - rather, writing in csv format.

I realise that is not structured logging, but this is a file sink, and csv is a common requirement, so I combined the two together, and arrived at this repo. Any pointers would be appreciated.

**Comment by bartelink** [comment]
https://github.com/cocowalla/serilog-sinks-file-header/tree/master/sample/Serilog.Sinks.File.Header.ConfigSample (found via https://twitter.com/nblumhardt/status/1120827210003169280)

**Comment by lonix1** [comment]
Thanks @bartelink. 

Actually I've been thinking about this and concluded it's a bad idea, I use serilog for logging, so I wanted everything logging-related to be done by serilog. But csv is completely different to structured logging. I think I'll write a custom logger for that, or use some library.
