### ISSUE TITLE
Issue with [serilog:write-to:File.outputTemplate]  in config (XML) file

### ISSUE THREAD

**Issue by sergiufilip** [serilog/serilog-sinks-file#260]
Couldn't find this documented explicitly but, based on inference this is the best 'key' I came up with but doesn't work (same identical syntax works in code):
```XML
<add key="serilog:write-to:File.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} 
                   [{Level:u3}] {Message:lj}{Properties}{NewLine}{Exception}"/>
```
Any suggestions ?
Thank you.

**Comment by cocowalla** [comment]
Could you please post *all* the keys you are using to configure the sink?

It's possibly something like [this](https://github.com/serilog/serilog-settings-appsettings/issues/6).

**Comment by sergiufilip** [comment]
Well, 
turned out to be my own fault here, as I missed referring the assembly that provides context enrichment - to begin with. 
The hint you provided @cocowalla was pivotal, as a switched to the JSON formatter (which outputs pretty much everything in the log record) and those attributes were missing too. Big thank you !

```XML
<add key="serilog:using:SerilogWeb.Classic" value="SerilogWeb.Classic" />
```
