### ISSUE TITLE
How to display log messages in ascending order - Newest at the top, oldest at bottom?

### ISSUE THREAD

**Issue by meeth23** [serilog/serilog-sinks-file#264]
I am trying to display my logs in ascending order - newest on the top, oldest at bottom. However, the default behavior displays the logs in descending order. Is there any way I can get the logs to display in ascending order?

**Comment by cocowalla** [comment]
Serilog writes new logs to the end of the file, just the same as every other logging framework. It's completely impractical to do it any other way.

If this is important to you, I'd suggest that you view your logs in some kind of editor that supports reversing the order, such as VSCode or [Notepad3](https://github.com/rizonesoft/Notepad3).
