### ISSUE TITLE
serilog No write

### ISSUE THREAD

**Issue by anan1213095357** [serilog/serilog-sinks-file#265]
serilog No write

`Log.Logger = new LoggerConfiguration()
               .MinimumLevel.Debug()
               .MinimumLevel.Information()
               .MinimumLevel.Error()
               .WriteTo.File($"C:\\logs\\log.txt", rollingInterval: RollingInterval.Day)
               //.WriteTo.File($"{AppContext.BaseDirectory}logs\\log.txt", rollingInterval: RollingInterval.Day)
               .CreateLogger();
            Log.Information("test");`

**Comment by bartelink** [comment]
Stackoverflow.com is the recommended place for usage questions such as this.
Please take the time to supply more complete information so people don't have to guess. Basic stuff like making sure the code is legible will also encourage people to engage with your question over there
