### ISSUE TITLE
Fixed file name

### ISSUE THREAD

**Issue by fdahlberg** [serilog/serilog-sinks-file#266]
Hi,

Is it possible to set up the file sink so that the latest logs always go to the same file? When the file is full I'd like to just delete it or alternatively back it up to another file. 
At the moment with rolling enabled it starts writing to a file with another name when the file is full. 
In our application we quite often have to ask the end user to send us the log file. If the file changes name all the time this makes it more complicated and error prone. 
This seems to work in another sink called "Serilog.Sinks.PersistentFile" but this does not have an official release.

Kind Regards
Fredrik Dahlberg

**Comment by bartelink** [comment]
See https://github.com/serilog/serilog-sinks-file/issues/40 - that third party sink is only implementation of that support - ultimately the Serilog Core maintainers only cover some core sinks; most others are maintained by third parties that have a vested interest and/or time to do so.

As covered in that issue and elsewhere, the stable filename semantics adds lots of complexity (and code) and comes with negatives as well as the obvious positive.

It's highly unlikely that this work will organically Just Happen by virtue of the maintainers of this Sink having the time and interest to provide support for this to the level that would be necessary.
