### ISSUE TITLE
Advanced File Retainment

### ISSUE THREAD

**Issue by sirmeepington** [serilog/serilog-sinks-file#268]
Hi,
Additional to the `retainedFileCountLimit`, is there a way to auto-compress after X amount of days/files, and then delete after an additional amount of days/files? If not, is there a community fork of the sink that implements this?

For example, after 7 days the logs are compressed, and after 30 days they're deleted.

**Comment by nblumhardt** [comment]
Hi! Please see https://github.com/serilog/serilog-sinks-file/issues/48 and https://github.com/cocowalla/serilog-sinks-file-gzip; thanks.
