### ISSUE TITLE
SQLite.Interop.dll in Serilog.Sinks.SQLite 5.5.0

### ISSUE THREAD

**Issue by sylverbee** [serilog/serilog-sinks-file#271]
I use Serilog.Sinks.SQLite 5.5.0 in an UWP project.
All submissions are rejected due to a fail in WACK. This version calls SQLite.Interop.dll that is not supported in UWP.
If I use version 5.0.0, it's fine.

Any solution?

**Comment by augustoproiete** [comment]
Hi @sylverbee this is not the repo for Serilog.Sinks.SQLite. I see you posted on the correct repo already https://github.com/saleem-mirza/serilog-sinks-sqlite/issues/42
