### ISSUE TITLE
Does retainedFileTimeLimit work on appsettings.json?

### ISSUE THREAD

**Issue by jhodges0845** [serilog/serilog-sinks-file#278]
Does retainedFileTimeLimit work on appsettings.json? 

If so how to implement?

**Comment by bartelink** [comment]
Best to ask this on stackoverflow with a `serilog` tag as:
- there's more traffic
- that's got more to do with the config mechanism than the file sink
- keeping this issues list for confirmed issues with the File sink lets the time maintainers spend on this sink be more focused

Be sure to include an example of what you have and what you want/need

(And my wild guess (I have never used config settings) is that it will work perfectly well as the mechanism is based on using reflection to map settings to properties on the sinks, i.e. it's not a question of whether some option has been "wired for cinfugurability")
