### ISSUE TITLE
MSSQLSink LogEvent column to be varbinary(max)

### ISSUE THREAD

**Issue by asiridissa** [serilog/serilog-sinks-file#290]
It is nice if MSSQLSink can support compressed LogEvent column. Their could be a configuration to turn the compression on and off.

MSSqlServer supports Compress function to GZip data in SQL level. https://learn.microsoft.com/en-us/sql/t-sql/functions/compress-transact-sql?view=sql-server-ver16.
Currently Binary columns a re not supported as a data type.
![image](https://github.com/serilog/serilog-sinks-file/assets/3539388/4387d2c9-c573-431b-9c59-e8b51e0bc2c7)

**Comment by nblumhardt** [comment]
Hi! This is the _Serilog.Sinks.File_ tracker; the repository where the MSSQL sink is developed is [here](https://github.com/serilog-mssql/serilog-sinks-mssqlserver). HTH!

**Comment by asiridissa** [comment]
Oops, Sorry
