### ISSUE TITLE
Any way to limit the size of a log file without "rolling" multiple files?

### ISSUE THREAD

**Issue by SoftCircuits** [serilog/serilog-sinks-file#293]
I'd prefer to just have a single log file. Is there any way to limit the size it can get, but don't stop logging?

Yes, I understand that the only way to do this is to delete the file when it gets too big. But I think this would be my preference.

**Comment by nblumhardt** [comment]
`rollOnFileSizeLimit: true, retainedFileCountLimit: 1` should be pretty close to what you need. HTH!
