### ISSUE TITLE
Is this library still being updated?

### ISSUE THREAD

**Issue by igloo15** [serilog/serilog-sinks-file#296]
Its been 2 years since the last nuget package update. Is this package still being updated? I can assume there would benefits to utilize some of the new features of dot net with spans etc in file logging.

**Comment by nblumhardt** [comment]
Hi! Yes, this package is maintained, but it's feature-complete according to its original goals, and very stable/reliable. Not changing much is a feature right now :-)

Although nothing significant has been added here recently, Serilog is composed of small building blocks. Things you might expect to find in the file sink are being developed/added through other projects, like _Serilog.Sinks.Async_, _Serilog.Sinks.Map_, and _Serilog.Expressions_. Hopefully some interesting bits and pieces there to check out.
