### ISSUE TITLE
deleteOldFileOnStartup

### ISSUE THREAD

**Issue by andreipet** [serilog/serilog-sinks-file#31]
Do you think a parameter like deleteOldFileOnStartup (NLog) could be implemented?
In unit testing I want my logs to contain only last run logs.
I can manually delete files from code configuration or processing external configs to find the sink file path but it will be awkward.
Thank you.

**Comment by nblumhardt** [comment]
Hi @andreipet - this sounds like it might be covered by https://github.com/serilog/serilog-sinks-rollingfile/issues/26 - what do you think? Cheers!

**Comment by andreipet** [comment]
It would be great. 
Maybe "retainedFileCountLimit": -1 or a negative value would do the trick.
Thank you for your time.

**Comment by nblumhardt** [comment]
Although this is a worthwhile one to consider, it seems stalled right now so I will close it until an opportunity to reevaluate comes our way. Thanks again!
