### ISSUE TITLE
[MAUI] I can't generate the log file

### ISSUE THREAD

**Issue by Victor-Porter** [serilog/serilog-sinks-file#310]
**Description**
I use the package to copy the logs to a ".log" file but it does not generate the directory or the file.

**Reproduction**

1. Create a new MAUI project.
2. Configure the logger on _MauiProgram.cs_.
3. Change the function _OnCounterClicked_ content on _MainPage.xaml.cs_ to generate some logs.
4. Launch the application.
5. Click the button to generate logs.
6. Find the logs directory and the logs file where you have stored the project.

**Expected behavior**
Have a file with the logs generated.

**Relevant package, tooling and runtime versions**
Serilog.Sinks.File: _5.0.1-dev-00972_

**Additional context**
[Link to the repository](https://github.com/MADSENSE/MADSENSE.MAUI.Sample.App/tree/serilog-write-to-file)

**Comment by bartelink** [comment]
Usage help questions are better addressed on stackoverflow.com

There are more eyes, and anyone watching this repo will also see questions tagged `serilog` over there
