### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [serilog/serilog-sinks-file#313]
**Is your feature request related to a problem? Please describe.**
The `PrivacyInfo.xcprivacy` manifest isrequired by Apple, please refer to the Apple's document https://developer.apple.com/documentation/bundleresources/privacy_manifest_files for the detailed information.

**Describe the solution you'd like**
A PrivacyInfo.xcprivacy for macOS

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-settings-configuration/issues/424
