### ISSUE TITLE
multi-process sharing not working

### ISSUE THREAD

**Issue by galastur** [serilog/serilog-sinks-file#315]
**Description**

I haven't used Serilog before, so apologies if I got something wrong.

It is my understanding that I should be able to log into a same file from different processes: 

> To enable multi-process shared log files, set shared to true:

I have two asp.net core APIs which should be writting to the same ERROR file, but it is failing. Only one API is writting to the error file at a  time

**Reproduction**

Run both APIs  (API-1 & API-2), and call the end point: WeatherForecast/GetWeatherError'  in both of them
Here is the sample project: [SerilogAPITester1.zip](https://github.com/user-attachments/files/16280357/SerilogAPITester1.zip)
**NOTE**: My second API is exactly the same as my first API. I will just modify the following two settings in the appsettings.json

"AppName": "Tester1" --> "AppName": "Tester2"
 "path": "E:/Logs/SerilogAPITester1-.txt" -->  "path": "E:/Logs/SerilogAPITester2-.txt"

**Expected behavior**

Expecting  both APIs to write to the same ERROR log file

**Relevant package, tooling and runtime versions**

VS 2022, .NET 8

![Screenshot 2024-07-18 093746](https://github.com/user-attachments/assets/d0ef58b7-4295-4baa-9e8c-74dfa9dc0ca7)

**Comment by bartelink** [comment]
You're best off posting a snippet of your wiring code and what you're expecting to happen to stackoverflow
You'll get many more eyes on it there than here; feel free to paste a link to the post when it's ready (though in general if you tag stuff `serilog`, anyone that answers here will have seen it there too)

**Comment by galastur** [comment]
Thanks, below is the more relevant code:

appsettings.json

  ```
"Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information",
        "System": "Warning"
      }
    },
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "File",
        "Args": {
          "path": "E:/Logs/SerilogAPITester1-.txt",
          "rollingInterval": "Day",
          "fileSizeLimitBytes": 50000000,
          "rollOnFileSizeLimit": true,
          "shared": true //so other apps can write here too
          //"outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}]) {Message} {NewLine} {Exception}"
        }
      },
      {
        "Name": "File",
        "Args": {
          "path": "E:/Logs/Errors-.txt",
          "rollingInterval": "Day",
          "fileSizeLimitBytes": 50000000,
          "rollOnFileSizeLimit": true,
          "shared": true, //so other apps can write here too
          "restrictedToMinimumLevel": "Error"
          //"outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}]) {Message} {NewLine} {Exception}"
        }
      }
    ]
    //"Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    //"Properties": {
    //  "Application": "Tester1",
    //  "Environment": "Prod"
    //}
  },
```

program.cs
```
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration).CreateLogger();
```

WeatherForecastController.cs
`
Log.Error("{AppName} returning error for testing", ConfigurationHelper.config.GetSection("AppName").Value);`

**Comment by bartelink** [comment]
>Thanks, below is the more relevant code:

This is github.com, not stackoverflow.com ;)

**Comment by bartelink** [comment]
If anyone have ideas, it's been posted to: https://stackoverflow.com/questions/78768537/serilog-multi-process-sharing-not-working-net-core-apis-not-able-to-write-t
