### ISSUE TITLE
Please provide a slightly more explicit way to specify the file log path.

### ISSUE THREAD

**Issue by bluekms** [serilog/serilog-sinks-file#319]
**Is your feature request related to a problem? Please describe.**
https://github.com/bluekms/SerilogFileTest/blob/main/SerilogFileTest/Program.cs
I want the log files to be created in `./.Logs`, which is a subpath of the directory where my program is running.
However, the path should not be `./Logs`.

**Describe the solution you'd like**
Please allow me to contribute to this project by PR.
I want to create a branch, work on it, and then request a merge to the main branch.

**Describe alternatives you've considered**
I'm trying to add a constructor for `PathRoller` that takes explicit arguments.

**Comment by nblumhardt** [comment]
Hi! I think you're looking for something like:

```csharp
var fullPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, relativePath);
```

where `relativePath` is something like `"./Logs/log-.txt`.

Note that the `File()` method expects a file name, not a directory name, so you'll need something like the example above.

HTH!,
Nick

**Comment by sorcerb** [comment]
Hello, we use:

`"path": "%LOGDIR%\\logs-.log",`

and in c#
```
 if (Environment.GetEnvironmentVariable("LOGDIR") == null)
            Environment.SetEnvironmentVariable("LOGDIR", $"{AppContext.BaseDirectory}\\app_data\\logs");
```

**Comment by bartelink** [comment]
Closing as Nick answered the original question
@sorcerb I realize you have a semi-related issue, but questions this are best triaged on StackOverflow - there's a high bar for adding complexity to naming here, and there's much more eyes on the `serilog` tag on SO than watchers on this repo.
In general, we try to keep this (and the other repos) issue trackers for fleshing out feature proposals and/or posting confirmed bugs with repros where possible, in order for anyone (including people like you) to be able to drive by and determine the state of play wrt open issues that have not been ruled our as inapplicable and/or insufficiently defined
