### ISSUE TITLE
Version 6.0.0 marked as vulnerable on Rider

### ISSUE THREAD

**Issue by mcanyucel** [serilog/serilog-sinks-file#329]
**Description**
The rider Nuget package manager marks the dependency `Serilog.Sinks.File` version 6.0.0 as vulnerable. But it does not specify any details. I am not sure this is considered a "bug" on serilog side per se, but I don't think it fits into feature request or help using sections either.

**Reproduction**
Use Jetbrains rider and install nuget package `Serilog.Sinks.File`

**Expected behavior**
No vulnerability warning.

**Relevant package, tooling and runtime versions**
version 6.0.0, on windows 11, dotnet 8, Jetbrains rider ide 2024.3 Build #RD-243.21565.191. Some more ide details:

> JetBrains Rider 2024.3
Build #RD-243.21565.191, built on November 13, 2024
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  com.github.copilot (1.5.29.7524)
  com.intellij.resharper.azure (4.3.4)

**Additional context**
A screenshot. 
![Screenshot 2024-11-22 130449](https://github.com/user-attachments/assets/34822b92-3a68-43b8-9dbf-f6680b876f1a)

**Comment by nblumhardt** [comment]
Looks like it might be a Rider bug? If anything shows up to the contrary please let us know; closing this as there's nothing we can action. Thanks for the heads-up though! 👍
