### ISSUE TITLE
SeriLog with Azure File Share or Blob

### ISSUE THREAD

**Issue by AnandPrakash05** [serilog/serilog-sinks-file#34]
Hi Team,

Please do let me know if we can use SeriLog with Azure File Share or Blob storage to supports encryption in transit?

Thank You!

**Comment by nblumhardt** [comment]
Hi @AnandPrakash05, thanks for the note.

This sink works with basic OS files, and should work with anything that behaves like them. Some investigation/experimentation will be required for other file types and file-systems. It's likely you'll need a custom sink for any file that's not accessible through a standard OS path.

HTH!
