### ISSUE TITLE
Incorrect AppSettings key

### ISSUE THREAD

**Issue by rmbrunet** [serilog/serilog-sinks-file#38]
When using the AppSettings package the correct key for the file path is "path" not "pathFormat" as the documentation says (leftover from previous version). Furthermore, I am getting a RollingInterval.Day not found error, but "Day" (or 3) seems to be working fine. 

Best regards, and thanks!

**Comment by nblumhardt** [comment]
Thanks for the note! I've fixed the use of `pathFormat` in the README, but I can't spot `"RollingInterval.Day"` in there (seems to use `"Day"`) - if I've missed one, could you please point me to it? Many thanks! :-)

**Comment by rmbrunet** [comment]
Hi. The RollingInterval.Day was my mistake: I thought -don't know why- that enumerations have to be fully specified (RollingInterval.Day instead of just Day).

Could you check the most recent open issue in the Email sink? Not reported by me but there is a problem there when the user is authenticated but the server expects anonymous access. 

Thanks again.

**Comment by nblumhardt** [comment]
:+1: thanks for the follow-up. The email sink is in need of some extra help, I'd love to dig into it but realistically probably won't get the time to figure this one out. All help appreciated over there! :-) Cheers

**Comment by tafs7** [comment]
@nblumhardt , I  hate to comment on an already closed issue....but I think it may be a good idea to specify the gotcha about the enum value in the README because that is not well documented elsewhere I've looked.  At least, add in the code snippet that also configures the `rollingInterval` property from appSettings.

**Comment by AlexaCodex** [comment]
rollingInterval : 1 works
