### ISSUE TITLE
Date-driven (rather than count-driven) file retention option

### ISSUE THREAD

**Issue by stephenpatten** [serilog/serilog-sinks-file#39]
Nick,

Aside from the fact that I (we) log too much, how do I keep all the log files created per day. It looks like we are only keeping the last 31 files. My thinking would be that with my config that the time period would trump the file size rolling behaviour. i.e. I should have 31 calendar days of logs and each day may have hundreds of files that rolled on size.. Hope that make some sense.  

Below you'll find my logger bootstrap and the packages I'm using.

Thank you,
Stephen 

	var filePath =
		$"{ConfigurationManager.AppSettings["LogFileBaseDir"]}\\ExternalFields_{Environment.MachineName}_.txt";

	const string Workflow_Serilog_V6 = "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}|{Level:u3}|{CorrelationId}|{MachineName}|{Application}|{ProcessId}|{ThreadId}|{SourceContext:l}|{Message}|{NewLine}{Exception}";

	Log.Logger = new LoggerConfiguration()
		.ReadFrom.AppSettings()
		.Enrich.FromLogContext()
		.Enrich.WithMachineName()
		.Enrich.WithProcessId()
		.Enrich.WithThreadId()
		.Enrich.WithProperty("Application", "ExternalFields")
		/*https://github.com/serilog/serilog-sinks-file*/
		.WriteTo.Async(a => 
				a.File(filePath, 
				outputTemplate: Workflow_Serilog_V6, 
				rollingInterval: RollingInterval.Day, 
				rollOnFileSizeLimit: true, 
				fileSizeLimitBytes: 104857600, 
				buffered: true,
				flushToDiskInterval: TimeSpan.FromMilliseconds(500)))
		.CreateLogger();

<packages>
  <package id="Serilog" version="2.5.0" targetFramework="net452" />
  <package id="Serilog.Enrichers.Environment" version="2.1.2" targetFramework="net452" />
  <package id="Serilog.Enrichers.Process" version="2.0.1" targetFramework="net452" />
  <package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net452" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net452" />
  <package id="Serilog.Settings.AppSettings" version="2.1.2" targetFramework="net452" />
  <package id="Serilog.Sinks.Async" version="1.1.0" targetFramework="net452" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net452" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net452" />
  <package id="SerilogMetrics" version="2.0.3" targetFramework="net452" />
</packages>

![image](https://user-images.githubusercontent.com/354728/32625616-9241df34-c541-11e7-9076-e55a571db5ee.png)

**Comment by stephenpatten** [comment]
Looks like the packages got truncated

<packages>
  <package id="Serilog" version="2.5.0" targetFramework="net452" />
  <package id="Serilog.Enrichers.Environment" version="2.1.2" targetFramework="net452" />
  <package id="Serilog.Enrichers.Process" version="2.0.1" targetFramework="net452" />
  <package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net452" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net452" />
  <package id="Serilog.Settings.AppSettings" version="2.1.2" targetFramework="net452" />
  <package id="Serilog.Sinks.Async" version="1.1.0" targetFramework="net452" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net452" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net452" />
  <package id="SerilogMetrics" version="2.0.3" targetFramework="net452" />
</packages>

**Comment by nblumhardt** [comment]
@stephenpatten thanks for the note; this is by design at the moment (it's `retainedFileCountLimit`, not a duration), but also a decent extension to consider in the future 👍

**Comment by stephenpatten** [comment]
Got it. 

So no matter how large these are, (1GB by default) I will only retain 90 of them regardless of the date of creation.

Another quick question, do I have the file settings for buffering and flushing setup correctly to be used in an asynchronous operation?      

      Log.Logger = new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithProcessId()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("Application", "ExternalFields")
                /*https://github.com/serilog/serilog-sinks-file*/
                .WriteTo.Async(a => 
                        a.File(filePath, 
                        outputTemplate: workflowSerilogV6,
                        retainedFileCountLimit: 90,
                        rollingInterval: RollingInterval.Day, 
                        rollOnFileSizeLimit: true, 
                        buffered: true,
                        flushToDiskInterval: TimeSpan.FromMilliseconds(500)))
                .CreateLogger();

**Comment by nblumhardt** [comment]
Looks good 👍

**Comment by se7vanj** [comment]
> @stephenpatten thanks for the note; this is by design at the moment (it's `retainedFileCountLimit`, not a duration), but also a decent extension to consider in the future 👍

@nblumhardt I tried AlternateRollingFile but often it writes 0KB, now I see SuperRollingFileAlternate available, but it will be helpful if we can see this feature on sinks-file itself.

**Comment by thiagosgarcia** [comment]
Just created PR #90 
Worked for me. Hope this helps.

**Comment by nblumhardt** [comment]
In the current -dev package; thanks @thiagosgarcia 👍
