### ISSUE TITLE
How to write JSON to file?

### ISSUE THREAD

**Issue by txchen** [serilog/serilog-sinks-file#4]
Is there a way to write the structured log to file (in json)?

**Comment by txchen** [comment]
I found https://github.com/nblumhardt/serilog-sinks-json and it is working.

However I still think serilog should support this officially.
Write json to log file can be useful when using some log shipper to read file and then write to log store (like elasticsearch). Although we already have the ES sink, I think writing json to file has the following advantages:

* more reliable to write to local file than remote service
* during development, we can easily see the structured data, without having to run a Seq instance or ElasticSearch.

**Comment by nblumhardt** [comment]
Hi! Yes, we've been working through a few changes to support this here. The API will look like:

```csharp
.WriteTo.File(new JsonFormatter(), "C:\\myapp.json")
```

The overload accepting an `ITextFormatter` is not present today, but will be added soon.

Regards,
Nick

**Comment by migellars** [comment]
> Hi! Yes, we've been working through a few changes to support this here. The API will look like:
> 
> ```cs
> .WriteTo.File(new JsonFormatter(), "C:\\myapp.json")
> ```
> 
> The overload accepting an `ITextFormatter` is not present today, but will be added soon.
> 
> Regards, Nick

Hello, how about you are fetching the with ReadFrom.Appsettings. how do I use new JsonFormatter
