### ISSUE TITLE
Combining file size limit and rolling days

### ISSUE THREAD

**Issue by danielwertheim** [serilog/serilog-sinks-file#41]
What combination should be used to get:
- Files of max X bytes, when reached, start a new file
- Keep max 10 days of logs

E.g

```
MyLog20171101-001.txt
MyLog20171101-002.txt
MyLog20171102-001.txt
MyLog20171102-002txt
MyLog20171102-003.txt
...
MyLog20171110-001.txt
...
Next day, all from 20171101 gets deleted
...
Next day, all from 20171102 gets deleted
...
```

**Comment by Shawn1874** [comment]
I would think that this would do it.

`.WriteTo.File("log.txt", fileSizeLimitBytes: <somevalue>, rollOnFileSizeLimit: true, rollingInterval: RollingInterval.Day)`

What do you mean by, "Next day, all from 20171101 gets deleted"?  I only see 6 files created before that.  I don't know what you are asking.  I think Serilog will simply stop creating log files when the limit is reached.

**Comment by ndrwwlf** [comment]
retainedFileCountLimt: 10

**Comment by nblumhardt** [comment]
I think you're looking for the same thing as #39 - closing as a duplicate. Cheers!

**Comment by ndrwwlf** [comment]
Thanks!
