### ISSUE TITLE
Empty NewLine 

### ISSUE THREAD

**Issue by sm-g** [serilog/serilog-sinks-file#46]
Config (both with `{Message}{NewLine}{Scope}{NewLine}{Exception}`):
```
"WriteTo": [
      {
        "Name": "Trace",
        "Args": {
          "outputTemplate": "{Level:u3}{EventId} {SourceContext}|{Message}{NewLine}{Scope}{NewLine}{Exception}"
        }
      },
      {
        "Name": "File",
        "Args": {
          "path": "D:\\my.log",
          "outputTemplate": "{Timestamp:HH:mm:ss}|{ThreadId:00}|{Level:u3}{EventId} ({SourceContext}) {Message}{NewLine}{Scope}{NewLine}{Exception}"
        }
      }
    ]
```

When there is no scope, empty line outputed to file, but not to trace.

In file:

```
14:16:15|18|INF (SoapCore.SoapEndpointMiddleware) No scope here

14:16:15|17|INF (Logging.PublishObserver) Scope
["Session 5c903286-9311-4d23-ac30-a40265e5b28a"]
14:16:15|17|INF (Logging.PublishObserver) Scope with exception
["Session 5c903286-9311-4d23-ac30-a40265e5b28a"]
System.InvalidOperationException:
	...
```

In trace:

```
INF SoapCore.SoapEndpointMiddleware|No scope here
INF Logging.PublishObserver|Scope
["Session 5c903286-9311-4d23-ac30-a40265e5b28a"]
INF Logging.PublishObserver|Scope with exception
["Session 5c903286-9311-4d23-ac30-a40265e5b28a"]
System.InvalidOperationException:
	...
```

Is that by design? Would be better to not output empty line into file.

**Comment by nblumhardt** [comment]
Hi @sm-g - yes, this is as expected. The `Trace` sink has to do trimming to get consistent output because of the way the tracing API works, which just happens to have a beneficial side-effect in this case. We've thrown ideas around a few times for some built-in conditional formatting - I have a proposal in the works that I hope to get back to later this year. For now, this one's "by design". Thanks for the detailed report, though!

**Comment by chtenb** [comment]
Is there already a way to make sure no empty lines are written?

**Comment by nblumhardt** [comment]
Hi @chtenb  - yes, the formatting facilities in https://github.com/serilog/serilog-expressions provide the conditionals etc. needed for this to work.

You should find what you're looking for in the recipes at: https://nblumhardt.com/2021/06/customize-serilog-text-output/ - let me know if it needs an addition :-)
