### ISSUE TITLE
What happens when sink can't write to file?

### ISSUE THREAD

**Issue by Ryder25** [serilog/serilog-sinks-file#49]
If I'm logging from an app on one computer to a file on another computer, what happens if the network becomes temporarily unavailable?

Will the logger no longer log any new events, or will it continue logging new events once the network becomes available?

If it stops completely how can I retry, or resume adding new events?

**Comment by nblumhardt** [comment]
@Ryder25 IIRC it'll attempt to re-open the file at the next rolling interval. Sorry about the slow reply - HTH. Closing as I'm guessing you've moved on from this one.
