### ISSUE TITLE
Files being rolled without cause?

### ISSUE THREAD

**Issue by stephenpatten** [serilog/serilog-sinks-file#51]
Nick,

Given this bootstrap

            var filePath =
                $"{ConfigurationManager.AppSettings["LogFileBaseDir"]}\\ExternalFields_{Environment.MachineName}_.txt";

             Log.Logger = new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithProcessId()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("Application", "ExternalFields")
                .WriteTo.Async(a => 
                        a.File(filePath, 
                        outputTemplate: LoggingConstants.CanonicalTemplate,
                        rollingInterval: RollingInterval.Day, 
                        rollOnFileSizeLimit: true, 
                        buffered: true,
                        flushToDiskInterval: TimeSpan.FromMilliseconds(500)))
                .CreateLogger();

and this key in the app settings section of the config

    <add key="serilog:minimum-level" value="Information" />

what would cause the files to be continually incremented like so:

![snap571](https://user-images.githubusercontent.com/354728/36615806-5d0320a0-1896-11e8-9ade-2c51518049e6.png)

In this case it is a single web application (above) writing the files and what's weird is that the production boxes (2) are working fine (below).

![snap572](https://user-images.githubusercontent.com/354728/36615893-bb2f1e54-1896-11e8-9671-cc5c6ddedb25.png)

Thank you,
Stephen

**Comment by nblumhardt** [comment]
Hi Stephen,

IIS will bring up a new app pool before completely shutting the old one down - my guess is that this is happening here. You can check via `SelfLog`, or by setting `shared: true` on the file (a good idea anyway).

Let me know if this helps, and have a great weekend!

(BTW, it's [not just me in here](https://github.com/serilog/serilog-sinks-file/watchers) these days ;-))

**Comment by stephenpatten** [comment]
HI,

SelfLog won't output to the File Sink will it? I'll need to write to another independent file...

**Comment by nblumhardt** [comment]
`SelfLog` can send output anywhere, but using the same file sink for it might be a bit circular :-)

You can use the delegate supplied to `SelfLog.Enable()` to write another text file, or to a logger configured to use the Windows event log, etc. :+1:

**Comment by stephenpatten** [comment]
Hello,

Here are the last 3 lines of the log ExternalFields_LIDD20EXTFLD01_**20180304**.txt

`2018-03-04 02:57:39.525 -08:00|INF|34d3c7d629894ad4af6037c1cec0055b|LIDD20EXTFLD01|ExternalFields|1400|25|||||PacificLife.Services.ExternalFields.Service.ExternalFieldService|EF Request "e5120132b2134834883fe068be56c8c4" "\\idevintfil01\IWMLogs\ExternalFields\Payloads\20180304\02\e5120132b2134834883fe068be56c8c4-ef-2018-03-04-02-57-39-509-3e05713bce154d469b5ce95f5887d1ef.xml"|
2018-03-04 02:57:39.587 -08:00|INF|34d3c7d629894ad4af6037c1cec0055b|LIDD20EXTFLD01|ExternalFields|1400|25|||||PacificLife.Services.ExternalFields.Service.ExternalFieldService|EF Response "e5120132b2134834883fe068be56c8c4" "\\idevintfil01\IWMLogs\ExternalFields\Payloads\20180304\02\e5120132b2134834883fe068be56c8c4-ef-2018-03-04-02-57-39-587-1ee7d57ddd6545bda947c3cc271204cd.xml"|
2018-03-04 02:57:40.712 -08:00|WRN||LIDD20EXTFLD01|ExternalFields|1400|58|||||Global|Application End "HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown""   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.Hosting.PipelineRuntime.StopProcessing()"|`


Then the file sync rolled the file to this ExternalFields_LIDD20EXTFLD01_**20180304_001**.txt

`2018-03-04 02:57:40.712 -08:00|WRN||LIDD20EXTFLD01|ExternalFields|1400|55|||||Global|Application End "HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown""   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.Hosting.PipelineRuntime.StopProcessing()"|
2018-03-04 02:58:09.527 -08:00|WRN||LIDD20EXTFLD01|ExternalFields|676|7|||||PayloadHelper|No files to delete matching this pattern "\\idevintfil01\IWMLogs\ExternalFields\Payloads" null|`

So you are correct, the current worker processes was being taken down and another was taking it's place. I just noticed this, the last log message is duplicated in the new file, is that by design? I kinda like it that way... I think, but can see potential downstream issues reporting on this event twice.


Before I close this I wanted to also let you know that when I added `shared: true` it tanked the application.

-Stephen

**Comment by stephenpatten** [comment]
I'm also interested in the internal logging and sending it to the event viewer, you you have some tests that have this setup bootstrapped somewhere I can "look at" ?

**Comment by nblumhardt** [comment]
Okay, sounds like we've tracked down the cause of the rolling :+1: 

It'd be great to get some clues as to why `shared:` is failing for you - I can't think of any examples of sending `SelfLog` to `EventLog` out there in the wild, but any logging mechanism that you can call inside:

```csharp
SelfLog.Enable(message => { /* log here */ });
```

should do the trick.

HTH!
Nick

**Comment by nblumhardt** [comment]
Closing as stale, but please jump in if you still need help with this.
