### ISSUE TITLE
How to change the log file name when using day-based rolling files in 4.0.0?

### ISSUE THREAD

**Issue by feO2x** [serilog/serilog-sinks-file#53]
As [you have announced recently](https://nblumhardt.com/2017/10/serilog-file-logging/), configuring rolling files is possible with the `Serilog.Sinks.File` package since version 4.0.0. **Is there any way to configure the output format for file names when using day-based rolling files?**

Consider the following logger configuration:

``` csharp
new LoggerConfiguration().WriteTo.File(filePath, rollingInterval: RollingInterval.Day);
```

When I set `filePath` to `MyLog.log` then the resulting file name would be `MyLog20180329.log`. How can I get to the following format: `2018-03-29 MyLog.log`? The `{Date}` specifier that was present in `Serilog.Sinks.RollingFile` seems to be not supported in this package.

I'm currently migrating one of our services from Log4Net to Serilog and we would like to keep the existing name template for our log files.

Thanks for your help in advance!

**Comment by natiki** [comment]
https://github.com/serilog/serilog-sinks-rollingfile/issues/66

**Comment by feO2x** [comment]
@nblumhardt When I placed `{Date}` in the pathFormat using only Serilog.Sinks.File 4.0.0 package, this was not resolved (the resulting log files were named "{Date} file20180522.log"). I now added Serilog.Sinks.Rollingfile and stick with the date format without dashes.

**Comment by nblumhardt** [comment]
Thanks for the follow-up @feO2x - I don't think it's likely we'll support the same placeholder-style formatting in this codebase, but _Serilog.Sinks.RollingFile_ is a good option.

If anyone's interested in looking at format specifier support there, i.e. to add the dashes, a proposal would be interesting; it's tricky, though, because of the need to reliably identify which files in a directory represent files in the rolling set, and to parse the dates back out of their filenames to ensure correct ordering when cleaning up old files.

Closing as I don't think we'll take direct action on this right now, but again, if anyone's keen enough to come up with a proposal for doing this cleanly/reliably in _Serilog.Sinks.RollingFile_ it'd be cool to get a discussion going there.

**Comment by Jehoel** [comment]
See this (now closed) PR: https://github.com/serilog/serilog-sinks-file/pull/84 - I'm working on it now

**Comment by gupta** [comment]
This issue is resolved here:
https://github.com/serilog/serilog-sinks-file/issues/148

**Comment by SimranRathore123** [comment]
> As [you have announced recently](https://nblumhardt.com/2017/10/serilog-file-logging/), configuring rolling files is possible with the `Serilog.Sinks.File` package since version 4.0.0. **Is there any way to configure the output format for file names when using day-based rolling files?**
> 
> Consider the following logger configuration:
> 
> ```cs
> new LoggerConfiguration().WriteTo.File(filePath, rollingInterval: RollingInterval.Day);
> ```
> 
> When I set `filePath` to `MyLog.log` then the resulting file name would be `MyLog20180329.log`. How can I get to the following format: `2018-03-29 MyLog.log`? The `{Date}` specifier that was present in `Serilog.Sinks.RollingFile` seems to be not supported in this package.
> 
> I'm currently migrating one of our services from Log4Net to Serilog and we would like to keep the existing name template for our log files.
> 
> Thanks for your help in advance!

Did you get the answer? If yes, then please share it with me. Actually I want the format to be something like this: LogFile_ddMMyyyy.txt  instead of LogFile_yyyyMMdd.txt

**Comment by SimranRathore123** [comment]
> As [you have announced recently](https://nblumhardt.com/2017/10/serilog-file-logging/), configuring rolling files is possible with the `Serilog.Sinks.File` package since version 4.0.0. **Is there any way to configure the output format for file names when using day-based rolling files?**
> 
> Consider the following logger configuration:
> 
> ```cs
> new LoggerConfiguration().WriteTo.File(filePath, rollingInterval: RollingInterval.Day);
> ```
> 
> When I set `filePath` to `MyLog.log` then the resulting file name would be `MyLog20180329.log`. How can I get to the following format: `2018-03-29 MyLog.log`? The `{Date}` specifier that was present in `Serilog.Sinks.RollingFile` seems to be not supported in this package.
> 
> I'm currently migrating one of our services from Log4Net to Serilog and we would like to keep the existing name template for our log files.
> 
> Thanks for your help in advance!

Did you get the answer? If yes, then please share it with me. Actually I want the format to be something like this: LogFile_ddMMyyyy.txt instead of LogFile_yyyyMMdd.txt

I would be really thankful.

**Comment by bartelink** [comment]
@SimranRathore123 If the links above to #148 and #84 don't provide you with enough information, I'd suggest logging a question showing what you've tried and what you're looking for on stackoverflow.com with the `serilog` tag - you'll get a quicker answer there, and anyone that watches this repo will see it there too
