### ISSUE TITLE
Question: directory separator character (forward or backslash)

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog-sinks-file#59]
The examples have this:
````
{
  "Serilog": {
    "WriteTo": [
      { "Name": "File", "Args": { "path": "log.txt", "rollingInterval": "Day" } }
    ]
  }
}
````

I want logs saved to `"logs"` subdirectory - in Windows it's `"logs\log.txt"` and *nix it's `"logs/log.txt"`.

In code I'd avoid this problem by getting the directory separator for the current environment. But this is done in `appsettings.json`. Any recommendations for ensuring portability?

**Comment by tsimbalar** [comment]
Hi,

wouldn't you have different config files for different environments anyway ? (I mean that you probably know whether your prod environment is a Unix or Windows OS and set up your config file accordingly).

Does that help ?

**Comment by lonix1** [comment]
Sure that makes sense. But we haven't decided yet how we'll end up hosting it. .NET Core is nice that we can leave such decisions to the end. Also some devs are running on nix and some windows, so it would be nice to avoid the problem somehow.

If there's no way to do this, that's fine. I was just wondering if the package takes this into account when it reads the config files or not?

**Comment by skomis-mm** [comment]
@lonix1 can you use `*nix` directory separator for both OS (I just checked it works on Windows 10)?
Another method I use personally for such things is that since this package expands environment variables you can prepare environment at the startup such as:
```
public static void Main(string[] args)
{
    Environment.SetEnvironmentVariable("DIR_SEPARATOR", Path.DirectorySeparatorChar.ToString());
```
and then use in the settings file:
```json
"path": "Logs%DIR_SEPARATOR%log.txt"
```

**Comment by lonix1** [comment]
@skomis-mm I didn't realise it works both ways on windows - thanks for that!
And that environment hack is clever, I'm gonna use that one too.
