### ISSUE TITLE
old logging system like `INF` used in documents

### ISSUE THREAD

**Issue by ranjan-ranjan** [serilog/serilog-sinks-file#66]
old logging system like `INF` used in documents

e.g., https://github.com/serilog/serilog-sinks-file

**Comment by nblumhardt** [comment]
Hi @ranjan-ranjan,

I'm not sure I follow what you're suggesting here, can you please send some more detail?

All the best,
Nick

**Comment by ranjan-ranjan** [comment]
![error](https://user-images.githubusercontent.com/16834561/48461616-84c2cf80-e7fa-11e8-8f01-a7456d9e36fe.png)

**Comment by nblumhardt** [comment]
Thanks - this is correct, the default output template in this sink now uses the `Level:u3` (three character uppercase) level formatting: https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs#L36

**Comment by ranjan-ranjan** [comment]
OK, thanks

I was using the default one.
