### ISSUE TITLE
fileSizeLimitBytes

### ISSUE THREAD

**Issue by ranjan-ranjan** [serilog/serilog-sinks-file#67]
What is the difference if we dont give `fileSizeLimitBytes` or we give it like this:
`<add key="serilog:write-to:File.fileSizeLimitBytes" />`?

In both the case `fileSizeLimitBytes` is set to 1 GB by default?

I have referred https://github.com/serilog/serilog-sinks-file

**Comment by nblumhardt** [comment]
Hi; you may need to verify, however I think the second example (XML config) will remove the limit, making file size unlimited.

**Comment by ranjan-ranjan** [comment]
Ok, Thanks,

same like `.WriteTo.File("log.txt", fileSizeLimitBytes: null)` ?

**Comment by nblumhardt** [comment]
Closing as stale; hope this is all working smoothly for you now 👍

**Comment by ranjan-ranjan** [comment]
I have implemented this
But, it would be better to mention the answer in Wiki
It will help others
