### ISSUE TITLE
retainedFileCountLimit

### ISSUE THREAD

**Issue by ranjan-ranjan** [serilog/serilog-sinks-file#68]
1. What is the difference if we dont give `retainedFileCountLimit` or we give it like this:
`<add key="serilog:write-to:File.retainedFileCountLimit" />`?

In both the case `retainedFileCountLimit` is set to 31?

2. Also, what does this mean - only 31 files will be saved max or one month old files will be saved?

3. Also, how the new log files will be written? Will the oldest log file be deleted and new ones will be written? Or the newer one will be deleted?

I have referred https://github.com/serilog/serilog-sinks-file

**Comment by nblumhardt** [comment]
Hi! Sorry we weren't able to get you a timely answer on this - I hope it's all working smoothly for you.

**Comment by ranjan-ranjan** [comment]
I have implemented this
But, it would be better to mention the answer in Wiki
It will help others

**Comment by progmars** [comment]
How to set `retainedFileCountLimit ` to indefinite using appSettings.json?

I tried `"retainedFileCountLimit": null`, `"retainedFileCountLimit": "null"`, `"retainedFileCountLimit": ""`, but they all crash Serilog with `System.InvalidOperationException' in Serilog.Settings.Configuration.dll`.
