### ISSUE TITLE
rollingInterval

### ISSUE THREAD

**Issue by ranjan-ranjan** [serilog/serilog-sinks-file#69]
I have given 

`<add key="serilog:write-to:RollingFile.rollingInterval" value="RollingInterval.Month" />`

in `App.config`

and have a file with the name `App-20181110.txt`

As per the documentation, it should appended to the same file.

But, it still created `App-20181114.txt`

I have referred https://github.com/serilog/serilog-sinks-file

**Comment by nblumhardt** [comment]
The value needs to be given as: `value="Month"` (`"Day"` in your other ticket). HTH!

**Comment by ranjan-ranjan** [comment]
Ok, got it

I have given
`<add key="serilog:write-to:File.rollingInterval" value="Month" />`

which creates files on per month basis, e.g., `App-201811.txt`

Ref: https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/RollingInterval.cs 


And one more thing -  in https://github.com/serilog/serilog-sinks-rollingfile, we have to give 

`<add key="serilog:write-to:RollingFile.pathFormat" value="log-{Date}.txt" />`

and in https://github.com/serilog/serilog-sinks-file

we have to give

`<add key="serilog:write-to:File.path" value="log.txt" />`

The value is different
