### ISSUE TITLE
Support parameteres in filename

### ISSUE THREAD

**Issue by ruant** [serilog/serilog-sinks-file#74]
Would be super handy to be able to use parameters in the filename.

Example:
One service that is used by two different users.
I would like to have two log files: `log-{username}.txt`
Where username is a property that's been pushed to the log context.

The filtering of the logging itself is already supported though `Filter`.
I know I could manually add these file sinks to the configuration, but that isn't gonna work if you got a bigger system with new users being added all the time.

**Comment by nblumhardt** [comment]
Hi @ruant, thanks for the note. Thought it's still WIP in a few places, https://github.com/serilog/serilog-sinks-map should help with this case. It's not likely this will make it into the file sink at this stage - though if we can get _Serilog.Sinks.Map_ working smoothly under all possible scenarios, there's a chance we'd migrate the functionality back in here.

HTH!

**Comment by ruant** [comment]
Didn't know about this one, thanks for pointing it out for me 👍 
This helps a lot, and solves what I'm after.
