### ISSUE TITLE
Add .Net Standard 2.0 target

### ISSUE THREAD

**Issue by vhatsura** [serilog/serilog-sinks-file#75]
According to [Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) it would be good to target .Net Standard 2.0 to benefit from having a smaller package graph.

I would appreciate to help with it.

**Comment by vhatsura** [comment]
@nblumhardt , where are you planning to release stable version?

**Comment by nblumhardt** [comment]
Hi @vhatsura - I've opened #78 to track, it probably just needs a quick check over by eye, and smoke-test of the `-pre` package; any feedback on that ticket would help. Cheers!
