### ISSUE TITLE
Serilog-sinks-file with Async not working after some time

### ISSUE THREAD

**Issue by se7vanj** [serilog/serilog-sinks-file#82]
@nblumhardt Using File Sink with Async, it works fine for hours and then suddenly (after days) its not writing any files. Selflog does not show any issues about this.

Appreciate if you can provide any assistance on this issue. Details below:

Earlier I was using Rolling package, AlternateRolling package and had similar issues. So decided to use File Sink to find out what's the actual problem?

I have also changed IIS AppPool setting "Disable Overlapped Recycle" to True.

1. CloseAndFlush is only to make sure that log events are not skipped during the Application Exit right?
2. In this case its an API hosted on IIS, I felt it is working fine if I call CloseAndFlush multiple times? but that would not be a best idea?
3. I am calling the CloseAndFlush method on the AppDomain.CurrentDomain.DomainUnload event defined in Global.ASAX, my assumption is without even calling this it should run fine? (because I am not talking about any logs that was submitted seconds ago, nothing is being written, AppPool was not stopped)

```cs
   public partial class Startup
   {
       public void Configuration(IAppBuilder app)
       {
          //
         var logger = new LoggerConfiguration()
               .MinimumLevel.ControlledBy(levelSwitch) //Dynamic levels

               // Sink 1 - SEQ
               //.WriteTo.Seq(StaticConfiguration.LogSeqServerUrl)

               // Sink 2 - FILE
               //XML configuration support has not yet been added for this wrapper, hence we have below code snippets instead fully from web.config file

               // File Sink - Async
               .WriteTo.Async(a => a.
                   File(string.Format(string.Format(filePath + ".log")),
                   rollingInterval: RollingInterval.Day,
                   outputTemplate: "{Message:lj}{NewLine}"
                   fileSizeLimitBytes: 40000000
                   shared: true
                   retainedFileCountLimit: 10
                   rollOnFileSizeLimit: true
                   //buffered: true, //not available when shared
                   //flushToDiskInterval: TimeSpan.FromMilliseconds(500)))

               .CreateLogger();

           // Configure PostSharp Logging to use Serilog
           var backend = new SerilogLoggingBackend(logger);
           backend.Options.Delimiter = ""
           backend.Options.AppendTrailingPeriod = false;
           backend.Options.UseSerilogFormatters = true;
           LoggingServices.DefaultBackend = backend;
       }
   }
```

**Comment by nblumhardt** [comment]
Hi! Sorry about the lack of response so far, I hope you figured this one out. Calling `CloseAndFlush()` multiple times will cause logging to stop - it sounds like this is your issue? If not, and you're still having trouble, let me know and I'll reopen/investigate further. Thanks!
