### ISSUE TITLE
New instance of logger creates new retention file even if size limit is not reached

### ISSUE THREAD

**Issue by tomasvilda** [serilog/serilog-sinks-file#83]
I would like to rollover when size is reached, that's working, but why it rolls when new instance of the same logger is created and last file haven't reached it's file size limit?

**Comment by nblumhardt** [comment]
Hi @tomasvilda - this is the behaviour if the file can't be opened. If you have multiple processes sharing the same set of files, make sure they're all using `shared: true` in the file sink configuration.

**Comment by tomasvilda** [comment]
Yes that's my fault, haven't disposed old logger before opening new one, now everything is fine. Thank you
