### ISSUE TITLE
Shared property not working

### ISSUE THREAD

**Issue by FinalFortune** [serilog/serilog-sinks-file#86]
Im trying to write logs and have the UI read them simultaneously, but when I call `File.Open(Path.Combine(directory, fileInfo.Name), FileMode.Open, FileAccess.Read))` it throws an exception and the file is already being used by a process.

The log is configured as such:  sublogger -> filter -> sinks.map -> sinks.async -> sinks.file
So logged items are logged to a uniquely named file filtered by their type and written asynchronously.

Config code:

```
          public SerilogProvisioner(LoggerConfiguration configuration, LogConfigResolver logConfigResolver, 
         string rootPath)
        {
            Relay = new LogRelay();
            LogConfigResolver = logConfigResolver;

            foreach (var key in logConfigResolver.GetTypes())
            {
                var resolution = logConfigResolver.Resolve(key);

                if (resolution != null && resolution.Output != null)
                {
                    configuration = configuration
                        .WriteTo.Logger(lc => lc
                            .Filter.ByIncludingOnly(Matching.FromSource(key.FullName))
                            .WriteTo.Map(resolution.PropertySelector ?? "LogId", (property, wt) =>
                            {
                                var logOptions = logConfigResolver.Resolve(key);
                                var path = Path.Combine(rootPath, logOptions.Output.Uri, property + "-.txt");

                                var logId = new LogId(key, property);
                                var relaySink = new LogRelaySink(logId, Path.Combine(rootPath, logOptions.Output.Uri));
                                Relay.AddRelay(relaySink);

                                switch (logOptions.Output.OutputType)
                                {
                                    case LogOutputType.File:
                                        wt.Async(a => a.File(
                                            path,
                                            shared: true,
                                            rollingInterval: RollingInterval.Day));
                                        break;
                                }

                                wt.Sink(relaySink);
                            }));
                }
            }
`
```

**Comment by nblumhardt** [comment]
Thanks for getting in touch. Any chance the file is open in another application - notepad.exe for example? If not, I'm afraid this could require a bit of debugging. Starting with a minimal console application that writes to a single file is a good strategy.

**Comment by FinalFortune** [comment]
I can't recall if I had notepad open, but I changed the access and share modes to read write in the open operation and it worked,  I will try again later with a more minimal implementation

**Comment by nblumhardt** [comment]
Sounds like you're unblocked, so I'll close this, but if you think you have found a bug please do let us know. Thanks!

**Comment by jaksonlin** [comment]
Hit the same issue when we do read all lines of the log file or using file stream without adding FileShare.ReadWrite:

Logger Configuration:

        logger = new LoggerConfiguration()
                .MinimumLevel.ControlledBy(loggingLevelSwitch)
                .Enrich.WithProperty("Component", component)
                .WriteTo.Console(outputTemplate: "{Timestamp:HH:mm:ss} [{Component}][{Level}] {Message}{NewLine}{Exception}")
                .WriteTo.File(logFile, shared:true, outputTemplate: "{Timestamp:HH:mm:ss} [{Component}][{Level}] {Message}{NewLine}{Exception}")
                .WriteTo.Logger(sLogger)
                .CreateLogger();

Code that hit this bug:

        string[] result1 = File.ReadAllLines(file);  <--- this won't work
        using (FileStream fs = new FileStream(file, FileMode.Open, FileAccess.Read))<---this won't work
           

W/A for this bug:

        using (FileStream fs = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))

Add FIleShare.ReadWrite

**Comment by nblumhardt** [comment]
Thanks for the info @jaksonlin. This isn't a bug as far as I can tell, just the normal functioning of file sharing/open modes. If you want to open a file in such a way that other processes may concurrently have the file open, too, then both processes must specify something from the `FileShare` enum. HTH!

**Comment by jaksonlin** [comment]
> Thanks for the info @jaksonlin. This isn't a bug as far as I can tell, just the normal functioning of file sharing/open modes. If you want to open a file in such a way that other processes may concurrently have the file open, too, then both processes must specify something from the `FileShare` enum. HTH!

Yes, understood. Thanks.

**Comment by seoriy** [comment]
@nblumhardt I have same problem. Seems like parameter "shared:true" isn't working.

**Comment by cocowalla** [comment]
@seoriy did you try opening the file using a `FileShare` enum, as demod in @jaksonlin code sample?

**Comment by hsynkrcf** [comment]
`logger = new LoggerConfiguration()
    .WriteTo.File("logs\\Log.txt", shared: true, rollingInterval: RollingInterval.Day)
    .CreateLogger();`
Shared: true -  this property did not work, ım found solution using logger.Dispose() for every write log

**Comment by mpowrie** [comment]
I find that real-time monitoring of log files with is not accurate for long running processes that are using the Serilog logging framework, because Serilog often has a lock on the file even with shared: true

The Serilog config snippet I'm using:
`Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.File(logFile, shared: true) 
            .CreateLogger();
`
