### ISSUE TITLE
Is there a way to pass json formatter using appsettings.json? 

### ISSUE THREAD

**Issue by skuzminoff** [serilog/serilog-sinks-file#89]
Somehow like this
```
"Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Fatal",
        "System": "Fatal",
      }
    },
    "Using": [
      "Serilog.Sinks.File",
    ],
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "pathFormat": "logs/log.log",
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog"
        }
      }
    ]
  }
```

**Comment by tsimbalar** [comment]
Hi,

yes this should work, and I believe you should be able to omit the `, Serilog` at the end of `"Serilog.Formatting.Json.JsonFormatter, Serilog"`


You can find more configuration examples in https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md

**Comment by tsimbalar** [comment]
Actually, no, the name of the parameter accepted by `WriteToFile(...)` is `path`, not `pathFormat` , as seen in : 

https://github.com/serilog/serilog-sinks-file/blob/0c65484c4d5daf655e49c66e392929a8b8b0afdb/src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs#L200-L214

so you should update your JSON to match that name.

I hope that helps.

**Comment by skuzminoff** [comment]
Thanks, @tsimbalar, it works.

**Comment by tsimbalar** [comment]
Cool ! 

Glad I could help

**Comment by mincasoft** [comment]
How to define UTF-8 encoding in json file?

**Comment by cocowalla** [comment]
@mincasoft the `WriteTo.File()` method takes an `Encoding` item as a parameter (you can see it in the [comment above](https://github.com/serilog/serilog-sinks-file/issues/89#issuecomment-472445865))
