### ISSUE TITLE
Using properties as part of the file name

### ISSUE THREAD

**Issue by fleed** [serilog/serilog-sinks-file#92]
Is it possible to use properties as part of the log file name?

I'd like to have a file name like "{Application}.log", where `{Application}` is a property.
I'm using it in an Asp.net core application, so I'd like to be able to write this file format in the appsettings.json:

```json
"Serilog": {
      "Using":  [ "Serilog.Sinks.File" ],
      "MinimumLevel": "Debug",
      "WriteTo": [
        { "Name": "File", "Args": { "path": "logs/{Application}.log", "rollingInterval": "Day", "fileSizeLimitBytes": 26214400, "rollOnFileSizeLimit":  true } }
      ],
      "Properties": {
        "Application": "MyApplicationName"
      }
```

**Comment by nblumhardt** [comment]
Hi! [_Serilog.Sinks.Map_](https://github.com/serilog/serilog-sinks-map) would do this, dynamically, but I think you'd be better off using something like Octopus Deploy to template your JSON config on deployment, if that kind of thing is an option. HTH!

**Comment by nblumhardt** [comment]
Hope you were able to get one of the above options working; we're about to release a 1.0 of _Serilog.Sinks.Map_, in case that helps.
